#ifndef CPKT_OPCUA_C89_BOUNDARY_PEER_H
#define CPKT_OPCUA_C89_BOUNDARY_PEER_H

#define CPKT_OPCUA_TEST_NS 1
#define CPKT_OPCUA_NATIVE_OBJECT_ID 5100
#define CPKT_OPCUA_NATIVE_INT_ID 5101
#define CPKT_OPCUA_NATIVE_BOOL_ID 5102
#define CPKT_OPCUA_NATIVE_STRING_ID 5103
#define CPKT_OPCUA_NATIVE_CHILD_ID 5104
#define CPKT_OPCUA_NATIVE_METHOD_ID 5105
#define CPKT_OPCUA_CLIENT_ADDED_OBJECT_ID 5106
#define CPKT_OPCUA_NATIVE_MULTI_METHOD_ID 5107
#define CPKT_OPCUA_NATIVE_BYTES_ID 5108
#define CPKT_OPCUA_CLIENT_ADDED_VARIABLE_ID 5109
#define CPKT_OPCUA_CLIENT_ADDED_CHILD_VARIABLE_ID 5110
#define CPKT_OPCUA_NATIVE_REFERENCE_TYPE_ID 5111
#define CPKT_OPCUA_NATIVE_VIEW_ID 5112
#define CPKT_OPCUA_CLIENT_ADDED_OBJECT_TYPE_ID 5113
#define CPKT_OPCUA_CLIENT_ADDED_VARIABLE_TYPE_ID 5114
#define CPKT_OPCUA_CLIENT_ADDED_REFERENCE_TYPE_ID 5115
#define CPKT_OPCUA_CLIENT_ADDED_DATA_TYPE_ID 5116
#define CPKT_OPCUA_CLIENT_ADDED_VIEW_ID 5117
#define CPKT_OPCUA_NATIVE_ARRAY_ID 5118
#define CPKT_OPCUA_NATIVE_BOOL_ARRAY_ID 5119
#define CPKT_OPCUA_NATIVE_DOUBLE_ARRAY_ID 5120
#define CPKT_OPCUA_NATIVE_STRING_ARRAY_ID 5121
#define CPKT_OPCUA_NATIVE_BYTES_ARRAY_ID 5122
#define CPKT_OPCUA_NATIVE_GUID_VALUE_ID 5123
#define CPKT_OPCUA_NATIVE_STATUS_VALUE_ID 5124
#define CPKT_OPCUA_NATIVE_QUALIFIED_NAME_VALUE_ID 5125
#define CPKT_OPCUA_NATIVE_LOCALIZED_TEXT_VALUE_ID 5126
#define CPKT_OPCUA_CLIENT_ADDED_ARRAY_VARIABLE_TYPE_ID 5127
#define CPKT_OPCUA_NATIVE_UINT64_VALUE_ID 5128
#define CPKT_OPCUA_NATIVE_DATETIME_VALUE_ID 5129
#define CPKT_OPCUA_NATIVE_UINT64_ARRAY_ID 5130
#define CPKT_OPCUA_NATIVE_DATETIME_ARRAY_ID 5131
#define CPKT_OPCUA_NATIVE_STATUS_ARRAY_ID 5132
#define CPKT_OPCUA_NATIVE_GUID_ARRAY_ID 5133
#define CPKT_OPCUA_NATIVE_QUALIFIED_NAME_ARRAY_ID 5134
#define CPKT_OPCUA_NATIVE_LOCALIZED_TEXT_ARRAY_ID 5135
#define CPKT_OPCUA_NATIVE_HISTORY_VALUE_ID 5136
#define CPKT_OPCUA_NATIVE_STRING_NODE_ID "nativeStringNode"

#define CPKT_OPCUA_FACADE_OBJECT_ID 5200
#define CPKT_OPCUA_FACADE_INT_ID 5201
#define CPKT_OPCUA_FACADE_DOUBLE_ID 5202
#define CPKT_OPCUA_FACADE_CHILD_ID 5203
#define CPKT_OPCUA_FACADE_METHOD_ID 5204
#define CPKT_OPCUA_FACADE_ECHO_METHOD_ID 5205
#define CPKT_OPCUA_FACADE_DELETED_OBJECT_ID 5206
#define CPKT_OPCUA_FACADE_MULTI_METHOD_ID 5207
#define CPKT_OPCUA_FACADE_BYTES_ID 5208
#define CPKT_OPCUA_FACADE_BYTES_METHOD_ID 5209
#define CPKT_OPCUA_FACADE_OBJECT_TYPE_ID 5210
#define CPKT_OPCUA_FACADE_VARIABLE_TYPE_ID 5211
#define CPKT_OPCUA_FACADE_REFERENCE_TYPE_ID 5212
#define CPKT_OPCUA_FACADE_DATA_TYPE_ID 5213
#define CPKT_OPCUA_FACADE_VIEW_ID 5214
#define CPKT_OPCUA_FACADE_ARRAY_ID 5215
#define CPKT_OPCUA_FACADE_BOOL_ARRAY_ID 5216
#define CPKT_OPCUA_FACADE_DOUBLE_ARRAY_ID 5217
#define CPKT_OPCUA_FACADE_STRING_ARRAY_ID 5218
#define CPKT_OPCUA_FACADE_BYTES_ARRAY_ID 5219
#define CPKT_OPCUA_FACADE_GUID_VALUE_ID 5220
#define CPKT_OPCUA_FACADE_STATUS_VALUE_ID 5221
#define CPKT_OPCUA_FACADE_QUALIFIED_NAME_VALUE_ID 5222
#define CPKT_OPCUA_FACADE_LOCALIZED_TEXT_VALUE_ID 5223
#define CPKT_OPCUA_FACADE_QUALIFIED_NAME_METHOD_ID 5224
#define CPKT_OPCUA_FACADE_LOCALIZED_TEXT_METHOD_ID 5225
#define CPKT_OPCUA_FACADE_EMPTY_METHOD_ID 5226
#define CPKT_OPCUA_FACADE_ARRAY_VARIABLE_TYPE_ID 5227
#define CPKT_OPCUA_FACADE_UINT64_VALUE_ID 5228
#define CPKT_OPCUA_FACADE_DATETIME_VALUE_ID 5229
#define CPKT_OPCUA_FACADE_UINT64_ARRAY_ID 5230
#define CPKT_OPCUA_FACADE_DATETIME_ARRAY_ID 5231
#define CPKT_OPCUA_FACADE_STATUS_ARRAY_ID 5232
#define CPKT_OPCUA_FACADE_GUID_ARRAY_ID 5233
#define CPKT_OPCUA_FACADE_QUALIFIED_NAME_ARRAY_ID 5234
#define CPKT_OPCUA_FACADE_LOCALIZED_TEXT_ARRAY_ID 5235
#define CPKT_OPCUA_FACADE_ASYNC_OBJECT_ID 5236
#define CPKT_OPCUA_FACADE_ASYNC_VARIABLE_ID 5237
#define CPKT_OPCUA_FACADE_STRING_NODE_ID "facadeStringNode"

#define CPKT_OPCUA_NATIVE_NAMESPACE_URI "urn:cpkt:opcua:native"
#define CPKT_OPCUA_FACADE_NAMESPACE_URI "urn:cpkt:opcua:facade"
#define CPKT_OPCUA_FACADE_APPLICATION_URI "urn:cpkt:opcua:facade-app"
#define CPKT_OPCUA_FACADE_PRODUCT_URI "urn:cpkt:opcua:facade-product"
#define CPKT_OPCUA_FACADE_APPLICATION_NAME "cpkt facade server"

typedef struct cpkt_opcua_c89_server_peer cpkt_opcua_c89_server_peer;
typedef int (*cpkt_opcua_c89_trigger_fn)(void *user);

int cpkt_opcua_c89_client_exercise_native_server(const char *endpoint);
int cpkt_opcua_c89_client_exercise_facade_server(const char *endpoint);
int cpkt_opcua_c89_client_monitor_facade_server_events(
    const char *endpoint, cpkt_opcua_c89_trigger_fn trigger_fn,
    void *trigger_user);

int cpkt_opcua_c89_server_peer_new(unsigned short port,
                                   cpkt_opcua_c89_server_peer **out,
                                   char *endpoint_buffer,
                                   unsigned long endpoint_buffer_size);
int cpkt_opcua_c89_server_peer_start(cpkt_opcua_c89_server_peer *peer);
int cpkt_opcua_c89_server_peer_iterate(cpkt_opcua_c89_server_peer *peer);
int cpkt_opcua_c89_server_peer_trigger_event(cpkt_opcua_c89_server_peer *peer);
int cpkt_opcua_c89_server_peer_shutdown(cpkt_opcua_c89_server_peer *peer);
void cpkt_opcua_c89_server_peer_free(cpkt_opcua_c89_server_peer *peer);

#endif
