foreach(_required CPKT_OPEN62541_BUILD_ROOT CPKT_OPENSSL_PREFIX CPKT_SHARED_LIBRARY_SUFFIX)
  if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
    message(FATAL_ERROR "${_required} is required")
  endif()
endforeach()

set(_expected_dir "${CPKT_OPENSSL_PREFIX}/lib/cmake/OpenSSL")
foreach(_linkage shared static)
  set(_cache "${CPKT_OPEN62541_BUILD_ROOT}/build-${_linkage}/CMakeCache.txt")
  if(NOT EXISTS "${_cache}")
    message(FATAL_ERROR "open62541 ${_linkage} cache is missing: ${_cache}")
  endif()
  file(STRINGS "${_cache}" _dir_entry REGEX "^OpenSSL_DIR:")
  string(REGEX REPLACE "^[^=]*=" "" _actual_dir "${_dir_entry}")
  if(NOT _actual_dir STREQUAL _expected_dir)
    message(FATAL_ERROR
      "open62541 ${_linkage} uses OpenSSL config ${_actual_dir}; expected ${_expected_dir}")
  endif()
  file(STRINGS "${_cache}" _static_entry REGEX "^OPENSSL_USE_STATIC_LIBS:")
  string(REGEX REPLACE "^[^=]*=" "" _actual_static "${_static_entry}")
  if(_linkage STREQUAL "static" AND NOT _actual_static STREQUAL "ON")
    message(FATAL_ERROR "open62541 static build did not select static OpenSSL")
  elseif(_linkage STREQUAL "shared" AND NOT _actual_static STREQUAL "OFF")
    message(FATAL_ERROR "open62541 shared build did not select shared OpenSSL")
  endif()
endforeach()

set(_shared_build "${CPKT_OPEN62541_BUILD_ROOT}/build-shared")
file(STRINGS "${_shared_build}/CMakeCache.txt" _generator_entry REGEX "^CMAKE_GENERATOR:")
string(REGEX REPLACE "^[^=]*=" "" _generator "${_generator_entry}")
if(_generator STREQUAL "Ninja")
  set(_link_plan "${_shared_build}/build.ninja")
elseif(_generator STREQUAL "Unix Makefiles")
  set(_link_plan "${_shared_build}/CMakeFiles/open62541.dir/link.txt")
else()
  message(FATAL_ERROR "unsupported open62541 build generator: ${_generator}")
endif()
if(NOT EXISTS "${_link_plan}")
  message(FATAL_ERROR "open62541 shared build plan is missing: ${_link_plan}")
endif()
if(_generator STREQUAL "Ninja")
  # Dependency edges elsewhere in the file do not prove what open62541 links.
  file(STRINGS "${_link_plan}" _lines)
  set(_in_link_rule OFF)
  foreach(_line IN LISTS _lines)
    if(_line MATCHES "^build [^:]+: C_SHARED_LIBRARY_LINKER__open62541_")
      set(_in_link_rule ON)
    elseif(_line MATCHES "^build ")
      set(_in_link_rule OFF)
    elseif(_in_link_rule AND _line MATCHES "^  LINK_LIBRARIES = (.*)$")
      set(_plan "${CMAKE_MATCH_1}")
      break()
    endif()
  endforeach()
  if(NOT DEFINED _plan)
    message(FATAL_ERROR "open62541 shared link command is missing: ${_link_plan}")
  endif()
else()
  file(READ "${_link_plan}" _plan)
endif()
set(_expected_ssl "${CPKT_OPENSSL_PREFIX}/lib/libssl${CPKT_SHARED_LIBRARY_SUFFIX}")
string(FIND "${_plan}" "${_expected_ssl}" _bundled_ssl_position)
if(_bundled_ssl_position EQUAL -1)
  message(FATAL_ERROR "open62541 shared build does not link bundled ${_expected_ssl}")
endif()
set(_expected_crypto "${CPKT_OPENSSL_PREFIX}/lib/libcrypto${CPKT_SHARED_LIBRARY_SUFFIX}")
string(FIND "${_plan}" "${_expected_crypto}" _bundled_crypto_position)
if(_bundled_crypto_position EQUAL -1)
  message(FATAL_ERROR "open62541 shared build does not link bundled ${_expected_crypto}")
endif()
