foreach(_required CPKT_OPEN62541_BUILD_ROOT CPKT_OPENSSL_PREFIX CPKT_SHARED_LIBRARY_SUFFIX)
  if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
    message(FATAL_ERROR "${_required} is required")
  endif()
endforeach()

set(_expected_dir "${CPKT_OPENSSL_PREFIX}/lib/cmake/OpenSSL")
foreach(_linkage shared static)
  set(_cache "${CPKT_OPEN62541_BUILD_ROOT}/build-${_linkage}/CMakeCache.txt")
  if(NOT EXISTS "${_cache}")
    message(FATAL_ERROR "open62541 ${_linkage} cache is missing: ${_cache}")
  endif()
  file(STRINGS "${_cache}" _dir_entry REGEX "^OpenSSL_DIR:")
  string(REGEX REPLACE "^[^=]*=" "" _actual_dir "${_dir_entry}")
  if(NOT _actual_dir STREQUAL _expected_dir)
    message(FATAL_ERROR
      "open62541 ${_linkage} uses OpenSSL config ${_actual_dir}; expected ${_expected_dir}")
  endif()
  file(STRINGS "${_cache}" _static_entry REGEX "^OPENSSL_USE_STATIC_LIBS:")
  string(REGEX REPLACE "^[^=]*=" "" _actual_static "${_static_entry}")
  if(_linkage STREQUAL "static" AND NOT _actual_static STREQUAL "ON")
    message(FATAL_ERROR "open62541 static build did not select static OpenSSL")
  elseif(_linkage STREQUAL "shared" AND NOT _actual_static STREQUAL "OFF")
    message(FATAL_ERROR "open62541 shared build did not select shared OpenSSL")
  endif()
endforeach()

set(_ninja "${CPKT_OPEN62541_BUILD_ROOT}/build-shared/build.ninja")
if(NOT EXISTS "${_ninja}")
  message(FATAL_ERROR "open62541 shared build plan is missing: ${_ninja}")
endif()
file(READ "${_ninja}" _plan)
set(_expected_ssl "${CPKT_OPENSSL_PREFIX}/lib/libssl${CPKT_SHARED_LIBRARY_SUFFIX}")
string(FIND "${_plan}" "${_expected_ssl}" _bundled_ssl_position)
if(_bundled_ssl_position EQUAL -1)
  message(FATAL_ERROR "open62541 shared build does not link bundled ${_expected_ssl}")
endif()
