"""Derive public descriptor kinds; expose descriptor ownership and introspection."""
from core_client_emitter import enum_declaration


def emit_dynamic(headers):
    declaration, _ = enum_declaration((headers / 'types.h').read_text(), 'DataTypeKind')
    return ['/** Native datatype classification; C89 value layout is exposed by descriptor metadata. */', declaration,
        '/** Public native descriptor metadata, with additional C89 size/alignment.',
        ' * Names and NodeId byte storage borrow from the descriptor. Never clear',
        ' * these views. memSize/overlayable describe upstream memory; publicSize',
        ' * and publicAlignment describe the C89 value layout. */',
        'typedef struct { const char *typeName; cpkt_opcua_NodeId typeId, binaryEncodingId, xmlEncodingId; size_t memSize, publicSize, publicAlignment; cpkt_opcua_DataTypeKind typeKind; cpkt_opcua_Boolean pointerFree, overlayable; size_t membersSize; } cpkt_opcua_DataTypeInfo;',
        '/** Full native public member metadata, plus C89 offsets. Enum members have',
        ' * a NULL memberType and enumValue instead. Names/descriptors are borrowed.',
        ' * Array offset addresses the pointer; lengthOffset addresses its size_t.',
        ' * Native padding retains its native meaning; never use it for C89 layout. */',
        'typedef struct { const char *memberName; const cpkt_opcua_Type *memberType; cpkt_opcua_Byte padding; cpkt_opcua_Boolean isArray, isOptional; size_t offset, lengthOffset; cpkt_opcua_Int64 enumValue; } cpkt_opcua_DataTypeMemberInfo;',
        '/** Copy descriptor metadata into info. Names and type identities borrow the descriptor; keep it alive while using the snapshot. */\ncpkt_opcua_StatusCode cpkt_opcua_DataType_getInfo(const cpkt_opcua_Type *type, cpkt_opcua_DataTypeInfo *info);',
        '/** Inspect a member by index. Name and memberType borrow descriptor metadata; no value conversion or descriptor ownership transfer occurs. */\ncpkt_opcua_StatusCode cpkt_opcua_DataType_getMember(const cpkt_opcua_Type *type, size_t index, cpkt_opcua_DataTypeMemberInfo *info);',
        '/** Find a public structure member. Output offset addresses the array length',
        ' * for arrays, otherwise the scalar/optional pointer. Unknown names return',
        ' * false and leave outputs unchanged. Descriptor and names are borrowed. */',
        'cpkt_opcua_Boolean cpkt_opcua_DataType_getStructMember(const cpkt_opcua_Type *type, const char *name, size_t *offset, const cpkt_opcua_Type **memberType, cpkt_opcua_Boolean *isArray);',
        '/** Build a native descriptor from the full public schema description and',
        ' * derive its C89 layout. Destination starts NULL. On success it owns the',
        ' * descriptor; delete it after every value/config/member reference has ended.',
        ' * Referenced custom descriptors are borrowed and must remain alive. Recursive',
        ' * arrays/optional members are supported. Native unsupported kinds/statuses',
        ' * remain native. Ordinary C89 structs use fields in schema order. For unions',
        ' * use a UInt32 switch field followed by a union of the declared arms. */',
        'cpkt_opcua_StatusCode cpkt_opcua_DataType_fromDescription(cpkt_opcua_Type **destination, const cpkt_opcua_ExtensionObject *description, const cpkt_opcua_DataTypeArray *customTypes);',
        '/** Copy an owned descriptor, retaining borrowed references to other types.',
        ' * Self-references point to the copy. Destination starts NULL. */',
        'cpkt_opcua_StatusCode cpkt_opcua_DataType_copy(const cpkt_opcua_Type *source, cpkt_opcua_Type **destination);',
        '/** Native public description of a descriptor. Output starts empty and owns',
        ' * the full generated ExtensionObject graph. Clear it after use. */',
        'cpkt_opcua_StatusCode cpkt_opcua_DataType_toDescription(const cpkt_opcua_Type *type, cpkt_opcua_ExtensionObject *description);',
        '/** Clear an individually owned descriptor after all users have quiesced.',
        ' * The descriptor becomes invalid but its allocation remains. Generated or',
        ' * array-owned borrowed descriptors are not individually clearable. */',
        'cpkt_opcua_StatusCode cpkt_opcua_DataType_clear(cpkt_opcua_Type *type);',
        '/** Delete an individually owned descriptor (including a cleared one).',
        ' * Borrowed generated or array-owned descriptors must not be deleted. */',
        'cpkt_opcua_StatusCode cpkt_opcua_DataType_delete(cpkt_opcua_Type *type);',
        '/** Delete an owned remote-descriptor array after every borrowed descriptor,',
        ' * value and configuration has quiesced. The whole graph is owned together.',
        ' * A manually constructed borrowed list is not deleted by this function. */',
        'cpkt_opcua_StatusCode cpkt_opcua_DataTypeArray_delete(cpkt_opcua_DataTypeArray *types);',
        '/** Retrieve native remote type definitions and derive their C89 layouts.',
        ' * Destination starts NULL. This does not install types into client config.',
        ' * The resulting array owns all returned descriptors; delete the whole array',
        ' * after every user has ended. Already-known config types remain borrowed. */',
        'cpkt_opcua_StatusCode cpkt_opcua_client_getRemoteDataTypes_typed(cpkt_opcua_client *client, size_t count, const cpkt_opcua_NodeId *nodes, cpkt_opcua_DataTypeArray **types);',
        '/** Add the complete native descriptor or schema description to the server.',
        ' * Native code owns its descriptor copy; references to other facade custom',
        ' * descriptors must remain alive through server deletion. Calls are serialized. */',
        'cpkt_opcua_StatusCode cpkt_opcua_server_addDataType_typed(cpkt_opcua_server *server, cpkt_opcua_NodeId parent, const cpkt_opcua_Type *type);',
        '/** Invoke native datatype creation from the full generated description. Description fields borrow through return; native interpretation and status are preserved. */\ncpkt_opcua_StatusCode cpkt_opcua_server_addDataTypeFromDescription_typed(cpkt_opcua_server *server, const cpkt_opcua_ExtensionObject *description);',
        '/** Find a generated or registered custom descriptor by native type identity.',
        ' * Returned descriptors borrow from their owner. No implicit copy occurs. */',
        'const cpkt_opcua_Type *cpkt_opcua_findDataType(const cpkt_opcua_NodeId *typeId);',
        '/** Find a standard generated descriptor by its native QualifiedName. */',
        'const cpkt_opcua_Type *cpkt_opcua_findDataTypeByName(const cpkt_opcua_QualifiedName *name);',
        '/** Native lookup in the supplied descriptor list, preserving the selected C89 descriptor identity. The result borrows its descriptor owner; NULL means no match or invalid metadata. */\nconst cpkt_opcua_Type *cpkt_opcua_findDataTypeWithCustom(const cpkt_opcua_NodeId *typeId, const cpkt_opcua_DataTypeArray *customTypes);',
        '/** Borrow the public descriptor for the native server datatype. Keep its configuration/type metadata alive through use; serialize with configuration changes. */\nconst cpkt_opcua_Type *cpkt_opcua_server_findDataType_typed(cpkt_opcua_server *server, const cpkt_opcua_NodeId *typeId);',
        '/** Complete borrowed server type list. The list view can change after the',
        ' * next native type/config change; never clear/delete it. Descriptors themselves',
        ' * remain valid through server deletion, including previous value references.',
        ' * Boundary conversion failure leaves output NULL; retrying this getter is safe.',
        ' * A successful native add followed by a conversion failure remains added. */',
        'cpkt_opcua_StatusCode cpkt_opcua_server_getDataTypes_typed(cpkt_opcua_server *server, const cpkt_opcua_DataTypeArray **types);']
