#ifndef CPKT_SQLITE_CONSTANTS_H
#define CPKT_SQLITE_CONSTANTS_H

/* Reviewed SQLite 3.53.4 public integer and string constants.
 * The native-to-facade decisions live in
 * tests/contracts/db_constant_bindings.json. */
#define CPKT_FTS5_TOKENIZE_AUX 0x0008
#define CPKT_FTS5_TOKENIZE_DOCUMENT 0x0004
#define CPKT_FTS5_TOKENIZE_PREFIX 0x0002
#define CPKT_FTS5_TOKENIZE_QUERY 0x0001
#define CPKT_FTS5_TOKEN_COLOCATED 0x0001
#define CPKT_SQLITE_ABORT 4
#define CPKT_SQLITE_ABORT_ROLLBACK (CPKT_SQLITE_ABORT | (2 << 8))
#define CPKT_SQLITE_ACCESS_EXISTS 0
#define CPKT_SQLITE_ACCESS_READ 2
#define CPKT_SQLITE_ACCESS_READWRITE 1
#define CPKT_SQLITE_ALTER_TABLE 26
#define CPKT_SQLITE_ANALYZE 28
#define CPKT_SQLITE_ANY 5
#define CPKT_SQLITE_ATTACH 24
#define CPKT_SQLITE_AUTH 23
#define CPKT_SQLITE_AUTH_USER (CPKT_SQLITE_AUTH | (1 << 8))
#define CPKT_SQLITE_BLOB 4
#define CPKT_SQLITE_BUSY 5
#define CPKT_SQLITE_BUSY_RECOVERY (CPKT_SQLITE_BUSY | (1 << 8))
#define CPKT_SQLITE_BUSY_SNAPSHOT (CPKT_SQLITE_BUSY | (2 << 8))
#define CPKT_SQLITE_BUSY_TIMEOUT (CPKT_SQLITE_BUSY | (3 << 8))
#define CPKT_SQLITE_CANTOPEN 14
#define CPKT_SQLITE_CANTOPEN_CONVPATH (CPKT_SQLITE_CANTOPEN | (4 << 8))
#define CPKT_SQLITE_CANTOPEN_DIRTYWAL (CPKT_SQLITE_CANTOPEN | (5 << 8))
#define CPKT_SQLITE_CANTOPEN_FULLPATH (CPKT_SQLITE_CANTOPEN | (3 << 8))
#define CPKT_SQLITE_CANTOPEN_ISDIR (CPKT_SQLITE_CANTOPEN | (2 << 8))
#define CPKT_SQLITE_CANTOPEN_NOTEMPDIR (CPKT_SQLITE_CANTOPEN | (1 << 8))
#define CPKT_SQLITE_CANTOPEN_SYMLINK (CPKT_SQLITE_CANTOPEN | (6 << 8))
#define CPKT_SQLITE_CARRAY_BLOB 4
#define CPKT_SQLITE_CARRAY_DOUBLE 2
#define CPKT_SQLITE_CARRAY_INT32 0
#define CPKT_SQLITE_CARRAY_INT64 1
#define CPKT_SQLITE_CARRAY_TEXT 3
#define CPKT_SQLITE_CHANGEGROUP_CONFIG_PATCHSET 1
#define CPKT_SQLITE_CHANGESETAPPLY_FKNOACTION 0x0008
#define CPKT_SQLITE_CHANGESETAPPLY_IGNORENOOP 0x0004
#define CPKT_SQLITE_CHANGESETAPPLY_INVERT 0x0002
#define CPKT_SQLITE_CHANGESETAPPLY_NOSAVEPOINT 0x0001
#define CPKT_SQLITE_CHANGESETAPPLY_NOUPDATELOOP 0x0010
#define CPKT_SQLITE_CHANGESETSTART_INVERT 0x0002
#define CPKT_SQLITE_CHANGESET_ABORT 2
#define CPKT_SQLITE_CHANGESET_CONFLICT 3
#define CPKT_SQLITE_CHANGESET_CONSTRAINT 4
#define CPKT_SQLITE_CHANGESET_DATA 1
#define CPKT_SQLITE_CHANGESET_FOREIGN_KEY 5
#define CPKT_SQLITE_CHANGESET_NOTFOUND 2
#define CPKT_SQLITE_CHANGESET_OMIT 0
#define CPKT_SQLITE_CHANGESET_REPLACE 1
#define CPKT_SQLITE_CHECKPOINT_FULL 1
#define CPKT_SQLITE_CHECKPOINT_NOOP -1
#define CPKT_SQLITE_CHECKPOINT_PASSIVE 0
#define CPKT_SQLITE_CHECKPOINT_RESTART 2
#define CPKT_SQLITE_CHECKPOINT_TRUNCATE 3
#define CPKT_SQLITE_CONFIG_COVERING_INDEX_SCAN 20
#define CPKT_SQLITE_CONFIG_GETMALLOC 5
#define CPKT_SQLITE_CONFIG_GETMUTEX 11
#define CPKT_SQLITE_CONFIG_GETPCACHE 15
#define CPKT_SQLITE_CONFIG_GETPCACHE2 19
#define CPKT_SQLITE_CONFIG_HEAP 8
#define CPKT_SQLITE_CONFIG_LOG 16
#define CPKT_SQLITE_CONFIG_LOOKASIDE 13
#define CPKT_SQLITE_CONFIG_MALLOC 4
#define CPKT_SQLITE_CONFIG_MEMDB_MAXSIZE 29
#define CPKT_SQLITE_CONFIG_MEMSTATUS 9
#define CPKT_SQLITE_CONFIG_MMAP_SIZE 22
#define CPKT_SQLITE_CONFIG_MULTITHREAD 2
#define CPKT_SQLITE_CONFIG_MUTEX 10
#define CPKT_SQLITE_CONFIG_PAGECACHE 7
#define CPKT_SQLITE_CONFIG_PCACHE 14
#define CPKT_SQLITE_CONFIG_PCACHE2 18
#define CPKT_SQLITE_CONFIG_PCACHE_HDRSZ 24
#define CPKT_SQLITE_CONFIG_PMASZ 25
#define CPKT_SQLITE_CONFIG_ROWID_IN_VIEW 30
#define CPKT_SQLITE_CONFIG_SCRATCH 6
#define CPKT_SQLITE_CONFIG_SERIALIZED 3
#define CPKT_SQLITE_CONFIG_SINGLETHREAD 1
#define CPKT_SQLITE_CONFIG_SMALL_MALLOC 27
#define CPKT_SQLITE_CONFIG_SORTERREF_SIZE 28
#define CPKT_SQLITE_CONFIG_SQLLOG 21
#define CPKT_SQLITE_CONFIG_STMTJRNL_SPILL 26
#define CPKT_SQLITE_CONFIG_URI 17
#define CPKT_SQLITE_CONSTRAINT 19
#define CPKT_SQLITE_CONSTRAINT_CHECK (CPKT_SQLITE_CONSTRAINT | (1 << 8))
#define CPKT_SQLITE_CONSTRAINT_COMMITHOOK (CPKT_SQLITE_CONSTRAINT | (2 << 8))
#define CPKT_SQLITE_CONSTRAINT_DATATYPE (CPKT_SQLITE_CONSTRAINT | (12 << 8))
#define CPKT_SQLITE_CONSTRAINT_FOREIGNKEY (CPKT_SQLITE_CONSTRAINT | (3 << 8))
#define CPKT_SQLITE_CONSTRAINT_FUNCTION (CPKT_SQLITE_CONSTRAINT | (4 << 8))
#define CPKT_SQLITE_CONSTRAINT_NOTNULL (CPKT_SQLITE_CONSTRAINT | (5 << 8))
#define CPKT_SQLITE_CONSTRAINT_PINNED (CPKT_SQLITE_CONSTRAINT | (11 << 8))
#define CPKT_SQLITE_CONSTRAINT_PRIMARYKEY (CPKT_SQLITE_CONSTRAINT | (6 << 8))
#define CPKT_SQLITE_CONSTRAINT_ROWID (CPKT_SQLITE_CONSTRAINT | (10 << 8))
#define CPKT_SQLITE_CONSTRAINT_TRIGGER (CPKT_SQLITE_CONSTRAINT | (7 << 8))
#define CPKT_SQLITE_CONSTRAINT_UNIQUE (CPKT_SQLITE_CONSTRAINT | (8 << 8))
#define CPKT_SQLITE_CONSTRAINT_VTAB (CPKT_SQLITE_CONSTRAINT | (9 << 8))
#define CPKT_SQLITE_COPY 0
#define CPKT_SQLITE_CORRUPT 11
#define CPKT_SQLITE_CORRUPT_INDEX (CPKT_SQLITE_CORRUPT | (3 << 8))
#define CPKT_SQLITE_CORRUPT_SEQUENCE (CPKT_SQLITE_CORRUPT | (2 << 8))
#define CPKT_SQLITE_CORRUPT_VTAB (CPKT_SQLITE_CORRUPT | (1 << 8))
#define CPKT_SQLITE_CREATE_INDEX 1
#define CPKT_SQLITE_CREATE_TABLE 2
#define CPKT_SQLITE_CREATE_TEMP_INDEX 3
#define CPKT_SQLITE_CREATE_TEMP_TABLE 4
#define CPKT_SQLITE_CREATE_TEMP_TRIGGER 5
#define CPKT_SQLITE_CREATE_TEMP_VIEW 6
#define CPKT_SQLITE_CREATE_TRIGGER 7
#define CPKT_SQLITE_CREATE_VIEW 8
#define CPKT_SQLITE_CREATE_VTABLE 29
#define CPKT_SQLITE_DBCONFIG_DEFENSIVE 1010
#define CPKT_SQLITE_DBCONFIG_DQS_DDL 1014
#define CPKT_SQLITE_DBCONFIG_DQS_DML 1013
#define CPKT_SQLITE_DBCONFIG_ENABLE_ATTACH_CREATE 1020
#define CPKT_SQLITE_DBCONFIG_ENABLE_ATTACH_WRITE 1021
#define CPKT_SQLITE_DBCONFIG_ENABLE_COMMENTS 1022
#define CPKT_SQLITE_DBCONFIG_ENABLE_FKEY 1002
#define CPKT_SQLITE_DBCONFIG_ENABLE_FTS3_TOKENIZER 1004
#define CPKT_SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION 1005
#define CPKT_SQLITE_DBCONFIG_ENABLE_QPSG 1007
#define CPKT_SQLITE_DBCONFIG_ENABLE_TRIGGER 1003
#define CPKT_SQLITE_DBCONFIG_ENABLE_VIEW 1015
#define CPKT_SQLITE_DBCONFIG_FP_DIGITS 1023
#define CPKT_SQLITE_DBCONFIG_LEGACY_ALTER_TABLE 1012
#define CPKT_SQLITE_DBCONFIG_LEGACY_FILE_FORMAT 1016
#define CPKT_SQLITE_DBCONFIG_LOOKASIDE 1001
#define CPKT_SQLITE_DBCONFIG_MAINDBNAME 1000
#define CPKT_SQLITE_DBCONFIG_MAX 1023
#define CPKT_SQLITE_DBCONFIG_NO_CKPT_ON_CLOSE 1006
#define CPKT_SQLITE_DBCONFIG_RESET_DATABASE 1009
#define CPKT_SQLITE_DBCONFIG_REVERSE_SCANORDER 1019
#define CPKT_SQLITE_DBCONFIG_STMT_SCANSTATUS 1018
#define CPKT_SQLITE_DBCONFIG_TRIGGER_EQP 1008
#define CPKT_SQLITE_DBCONFIG_TRUSTED_SCHEMA 1017
#define CPKT_SQLITE_DBCONFIG_WRITABLE_SCHEMA 1011
#define CPKT_SQLITE_DBSTATUS_CACHE_HIT 7
#define CPKT_SQLITE_DBSTATUS_CACHE_MISS 8
#define CPKT_SQLITE_DBSTATUS_CACHE_SPILL 12
#define CPKT_SQLITE_DBSTATUS_CACHE_USED 1
#define CPKT_SQLITE_DBSTATUS_CACHE_USED_SHARED 11
#define CPKT_SQLITE_DBSTATUS_CACHE_WRITE 9
#define CPKT_SQLITE_DBSTATUS_DEFERRED_FKS 10
#define CPKT_SQLITE_DBSTATUS_LOOKASIDE_HIT 4
#define CPKT_SQLITE_DBSTATUS_LOOKASIDE_MISS_FULL 6
#define CPKT_SQLITE_DBSTATUS_LOOKASIDE_MISS_SIZE 5
#define CPKT_SQLITE_DBSTATUS_LOOKASIDE_USED 0
#define CPKT_SQLITE_DBSTATUS_MAX 13
#define CPKT_SQLITE_DBSTATUS_SCHEMA_USED 2
#define CPKT_SQLITE_DBSTATUS_STMT_USED 3
#define CPKT_SQLITE_DBSTATUS_TEMPBUF_SPILL 13
#define CPKT_SQLITE_DELETE 9
#define CPKT_SQLITE_DENY 1
#define CPKT_SQLITE_DESERIALIZE_FREEONCLOSE 1
#define CPKT_SQLITE_DESERIALIZE_READONLY 4
#define CPKT_SQLITE_DESERIALIZE_RESIZEABLE 2
#define CPKT_SQLITE_DETACH 25
#define CPKT_SQLITE_DETERMINISTIC 0x000000800
#define CPKT_SQLITE_DIRECTONLY 0x000080000
#define CPKT_SQLITE_DONE 101
#define CPKT_SQLITE_DROP_INDEX 10
#define CPKT_SQLITE_DROP_TABLE 11
#define CPKT_SQLITE_DROP_TEMP_INDEX 12
#define CPKT_SQLITE_DROP_TEMP_TABLE 13
#define CPKT_SQLITE_DROP_TEMP_TRIGGER 14
#define CPKT_SQLITE_DROP_TEMP_VIEW 15
#define CPKT_SQLITE_DROP_TRIGGER 16
#define CPKT_SQLITE_DROP_VIEW 17
#define CPKT_SQLITE_DROP_VTABLE 30
#define CPKT_SQLITE_EMPTY 16
#define CPKT_SQLITE_ENABLE_CARRAY 1
#define CPKT_SQLITE_ENABLE_NORMALIZE 1
#define CPKT_SQLITE_ENABLE_PREUPDATE_HOOK 1
#define CPKT_SQLITE_ENABLE_SESSION 1
#define CPKT_SQLITE_ERROR 1
#define CPKT_SQLITE_ERROR_KEY (CPKT_SQLITE_ERROR | (5 << 8))
#define CPKT_SQLITE_ERROR_MISSING_COLLSEQ (CPKT_SQLITE_ERROR | (1 << 8))
#define CPKT_SQLITE_ERROR_RESERVESIZE (CPKT_SQLITE_ERROR | (4 << 8))
#define CPKT_SQLITE_ERROR_RETRY (CPKT_SQLITE_ERROR | (2 << 8))
#define CPKT_SQLITE_ERROR_SNAPSHOT (CPKT_SQLITE_ERROR | (3 << 8))
#define CPKT_SQLITE_ERROR_UNABLE (CPKT_SQLITE_ERROR | (6 << 8))
#define CPKT_SQLITE_FAIL 3
#define CPKT_SQLITE_FCNTL_BEGIN_ATOMIC_WRITE 31
#define CPKT_SQLITE_FCNTL_BLOCK_ON_CONNECT 44
#define CPKT_SQLITE_FCNTL_BUSYHANDLER 15
#define CPKT_SQLITE_FCNTL_CHUNK_SIZE 6
#define CPKT_SQLITE_FCNTL_CKPT_DONE 37
#define CPKT_SQLITE_FCNTL_CKPT_START 39
#define CPKT_SQLITE_FCNTL_CKSM_FILE 41
#define CPKT_SQLITE_FCNTL_COMMIT_ATOMIC_WRITE 32
#define CPKT_SQLITE_FCNTL_COMMIT_PHASETWO 22
#define CPKT_SQLITE_FCNTL_DATA_VERSION 35
#define CPKT_SQLITE_FCNTL_EXTERNAL_READER 40
#define CPKT_SQLITE_FCNTL_FILESTAT 45
#define CPKT_SQLITE_FCNTL_FILE_POINTER 7
#define CPKT_SQLITE_FCNTL_GET_LOCKPROXYFILE 2
#define CPKT_SQLITE_FCNTL_HAS_MOVED 20
#define CPKT_SQLITE_FCNTL_JOURNAL_POINTER 28
#define CPKT_SQLITE_FCNTL_LAST_ERRNO 4
#define CPKT_SQLITE_FCNTL_LOCKSTATE 1
#define CPKT_SQLITE_FCNTL_LOCK_TIMEOUT 34
#define CPKT_SQLITE_FCNTL_MMAP_SIZE 18
#define CPKT_SQLITE_FCNTL_NULL_IO 43
#define CPKT_SQLITE_FCNTL_OVERWRITE 11
#define CPKT_SQLITE_FCNTL_PDB 30
#define CPKT_SQLITE_FCNTL_PERSIST_WAL 10
#define CPKT_SQLITE_FCNTL_POWERSAFE_OVERWRITE 13
#define CPKT_SQLITE_FCNTL_PRAGMA 14
#define CPKT_SQLITE_FCNTL_RBU 26
#define CPKT_SQLITE_FCNTL_RESERVE_BYTES 38
#define CPKT_SQLITE_FCNTL_RESET_CACHE 42
#define CPKT_SQLITE_FCNTL_ROLLBACK_ATOMIC_WRITE 33
#define CPKT_SQLITE_FCNTL_SET_LOCKPROXYFILE 3
#define CPKT_SQLITE_FCNTL_SIZE_HINT 5
#define CPKT_SQLITE_FCNTL_SIZE_LIMIT 36
#define CPKT_SQLITE_FCNTL_SYNC 21
#define CPKT_SQLITE_FCNTL_SYNC_OMITTED 8
#define CPKT_SQLITE_FCNTL_TEMPFILENAME 16
#define CPKT_SQLITE_FCNTL_TRACE 19
#define CPKT_SQLITE_FCNTL_VFSNAME 12
#define CPKT_SQLITE_FCNTL_VFS_POINTER 27
#define CPKT_SQLITE_FCNTL_WAL_BLOCK 24
#define CPKT_SQLITE_FCNTL_ZIPVFS 25
#define CPKT_SQLITE_FLOAT 2
#define CPKT_SQLITE_FORMAT 24
#define CPKT_SQLITE_FULL 13
#define CPKT_SQLITE_FUNCTION 31
#define CPKT_SQLITE_GET_LOCKPROXYFILE CPKT_SQLITE_FCNTL_GET_LOCKPROXYFILE
#define CPKT_SQLITE_IGNORE 2
#define CPKT_SQLITE_INDEX_CONSTRAINT_EQ 2
#define CPKT_SQLITE_INDEX_CONSTRAINT_FUNCTION 150
#define CPKT_SQLITE_INDEX_CONSTRAINT_GE 32
#define CPKT_SQLITE_INDEX_CONSTRAINT_GLOB 66
#define CPKT_SQLITE_INDEX_CONSTRAINT_GT 4
#define CPKT_SQLITE_INDEX_CONSTRAINT_IS 72
#define CPKT_SQLITE_INDEX_CONSTRAINT_ISNOT 69
#define CPKT_SQLITE_INDEX_CONSTRAINT_ISNOTNULL 70
#define CPKT_SQLITE_INDEX_CONSTRAINT_ISNULL 71
#define CPKT_SQLITE_INDEX_CONSTRAINT_LE 8
#define CPKT_SQLITE_INDEX_CONSTRAINT_LIKE 65
#define CPKT_SQLITE_INDEX_CONSTRAINT_LIMIT 73
#define CPKT_SQLITE_INDEX_CONSTRAINT_LT 16
#define CPKT_SQLITE_INDEX_CONSTRAINT_MATCH 64
#define CPKT_SQLITE_INDEX_CONSTRAINT_NE 68
#define CPKT_SQLITE_INDEX_CONSTRAINT_OFFSET 74
#define CPKT_SQLITE_INDEX_CONSTRAINT_REGEXP 67
#define CPKT_SQLITE_INDEX_SCAN_HEX 0x00000002
#define CPKT_SQLITE_INDEX_SCAN_UNIQUE 0x00000001
#define CPKT_SQLITE_INNOCUOUS 0x000200000
#define CPKT_SQLITE_INSERT 18
#define CPKT_SQLITE_INTEGER 1
#define CPKT_SQLITE_INTERNAL 2
#define CPKT_SQLITE_INTERRUPT 9
#define CPKT_SQLITE_IOCAP_ATOMIC 0x00000001
#define CPKT_SQLITE_IOCAP_ATOMIC16K 0x00000040
#define CPKT_SQLITE_IOCAP_ATOMIC1K 0x00000004
#define CPKT_SQLITE_IOCAP_ATOMIC2K 0x00000008
#define CPKT_SQLITE_IOCAP_ATOMIC32K 0x00000080
#define CPKT_SQLITE_IOCAP_ATOMIC4K 0x00000010
#define CPKT_SQLITE_IOCAP_ATOMIC512 0x00000002
#define CPKT_SQLITE_IOCAP_ATOMIC64K 0x00000100
#define CPKT_SQLITE_IOCAP_ATOMIC8K 0x00000020
#define CPKT_SQLITE_IOCAP_BATCH_ATOMIC 0x00004000
#define CPKT_SQLITE_IOCAP_IMMUTABLE 0x00002000
#define CPKT_SQLITE_IOCAP_POWERSAFE_OVERWRITE 0x00001000
#define CPKT_SQLITE_IOCAP_SAFE_APPEND 0x00000200
#define CPKT_SQLITE_IOCAP_SEQUENTIAL 0x00000400
#define CPKT_SQLITE_IOCAP_SUBPAGE_READ 0x00008000
#define CPKT_SQLITE_IOCAP_UNDELETABLE_WHEN_OPEN 0x00000800
#define CPKT_SQLITE_IOERR 10
#define CPKT_SQLITE_IOERR_ACCESS (CPKT_SQLITE_IOERR | (13 << 8))
#define CPKT_SQLITE_IOERR_AUTH (CPKT_SQLITE_IOERR | (28 << 8))
#define CPKT_SQLITE_IOERR_BADKEY (CPKT_SQLITE_IOERR | (35 << 8))
#define CPKT_SQLITE_IOERR_BEGIN_ATOMIC (CPKT_SQLITE_IOERR | (29 << 8))
#define CPKT_SQLITE_IOERR_BLOCKED (CPKT_SQLITE_IOERR | (11 << 8))
#define CPKT_SQLITE_IOERR_CHECKRESERVEDLOCK (CPKT_SQLITE_IOERR | (14 << 8))
#define CPKT_SQLITE_IOERR_CLOSE (CPKT_SQLITE_IOERR | (16 << 8))
#define CPKT_SQLITE_IOERR_CODEC (CPKT_SQLITE_IOERR | (36 << 8))
#define CPKT_SQLITE_IOERR_COMMIT_ATOMIC (CPKT_SQLITE_IOERR | (30 << 8))
#define CPKT_SQLITE_IOERR_CONVPATH (CPKT_SQLITE_IOERR | (26 << 8))
#define CPKT_SQLITE_IOERR_CORRUPTFS (CPKT_SQLITE_IOERR | (33 << 8))
#define CPKT_SQLITE_IOERR_DATA (CPKT_SQLITE_IOERR | (32 << 8))
#define CPKT_SQLITE_IOERR_DELETE (CPKT_SQLITE_IOERR | (10 << 8))
#define CPKT_SQLITE_IOERR_DELETE_NOENT (CPKT_SQLITE_IOERR | (23 << 8))
#define CPKT_SQLITE_IOERR_DIR_CLOSE (CPKT_SQLITE_IOERR | (17 << 8))
#define CPKT_SQLITE_IOERR_DIR_FSYNC (CPKT_SQLITE_IOERR | (5 << 8))
#define CPKT_SQLITE_IOERR_FSTAT (CPKT_SQLITE_IOERR | (7 << 8))
#define CPKT_SQLITE_IOERR_FSYNC (CPKT_SQLITE_IOERR | (4 << 8))
#define CPKT_SQLITE_IOERR_GETTEMPPATH (CPKT_SQLITE_IOERR | (25 << 8))
#define CPKT_SQLITE_IOERR_IN_PAGE (CPKT_SQLITE_IOERR | (34 << 8))
#define CPKT_SQLITE_IOERR_LOCK (CPKT_SQLITE_IOERR | (15 << 8))
#define CPKT_SQLITE_IOERR_MMAP (CPKT_SQLITE_IOERR | (24 << 8))
#define CPKT_SQLITE_IOERR_NOMEM (CPKT_SQLITE_IOERR | (12 << 8))
#define CPKT_SQLITE_IOERR_RDLOCK (CPKT_SQLITE_IOERR | (9 << 8))
#define CPKT_SQLITE_IOERR_READ (CPKT_SQLITE_IOERR | (1 << 8))
#define CPKT_SQLITE_IOERR_ROLLBACK_ATOMIC (CPKT_SQLITE_IOERR | (31 << 8))
#define CPKT_SQLITE_IOERR_SEEK (CPKT_SQLITE_IOERR | (22 << 8))
#define CPKT_SQLITE_IOERR_SHMLOCK (CPKT_SQLITE_IOERR | (20 << 8))
#define CPKT_SQLITE_IOERR_SHMMAP (CPKT_SQLITE_IOERR | (21 << 8))
#define CPKT_SQLITE_IOERR_SHMOPEN (CPKT_SQLITE_IOERR | (18 << 8))
#define CPKT_SQLITE_IOERR_SHMSIZE (CPKT_SQLITE_IOERR | (19 << 8))
#define CPKT_SQLITE_IOERR_SHORT_READ (CPKT_SQLITE_IOERR | (2 << 8))
#define CPKT_SQLITE_IOERR_TRUNCATE (CPKT_SQLITE_IOERR | (6 << 8))
#define CPKT_SQLITE_IOERR_UNLOCK (CPKT_SQLITE_IOERR | (8 << 8))
#define CPKT_SQLITE_IOERR_VNODE (CPKT_SQLITE_IOERR | (27 << 8))
#define CPKT_SQLITE_IOERR_WRITE (CPKT_SQLITE_IOERR | (3 << 8))
#define CPKT_SQLITE_LAST_ERRNO CPKT_SQLITE_FCNTL_LAST_ERRNO
#define CPKT_SQLITE_LIMIT_ATTACHED 7
#define CPKT_SQLITE_LIMIT_COLUMN 2
#define CPKT_SQLITE_LIMIT_COMPOUND_SELECT 4
#define CPKT_SQLITE_LIMIT_EXPR_DEPTH 3
#define CPKT_SQLITE_LIMIT_FUNCTION_ARG 6
#define CPKT_SQLITE_LIMIT_LENGTH 0
#define CPKT_SQLITE_LIMIT_LIKE_PATTERN_LENGTH 8
#define CPKT_SQLITE_LIMIT_PARSER_DEPTH 12
#define CPKT_SQLITE_LIMIT_SQL_LENGTH 1
#define CPKT_SQLITE_LIMIT_TRIGGER_DEPTH 10
#define CPKT_SQLITE_LIMIT_VARIABLE_NUMBER 9
#define CPKT_SQLITE_LIMIT_VDBE_OP 5
#define CPKT_SQLITE_LIMIT_WORKER_THREADS 11
#define CPKT_SQLITE_LOCKED 6
#define CPKT_SQLITE_LOCKED_SHAREDCACHE (CPKT_SQLITE_LOCKED | (1 << 8))
#define CPKT_SQLITE_LOCKED_VTAB (CPKT_SQLITE_LOCKED | (2 << 8))
#define CPKT_SQLITE_LOCK_EXCLUSIVE 4
#define CPKT_SQLITE_LOCK_NONE 0
#define CPKT_SQLITE_LOCK_PENDING 3
#define CPKT_SQLITE_LOCK_RESERVED 2
#define CPKT_SQLITE_LOCK_SHARED 1
#define CPKT_SQLITE_MISMATCH 20
#define CPKT_SQLITE_MISUSE 21
#define CPKT_SQLITE_MUTEX_FAST 0
#define CPKT_SQLITE_MUTEX_RECURSIVE 1
#define CPKT_SQLITE_MUTEX_STATIC_APP1 8
#define CPKT_SQLITE_MUTEX_STATIC_APP2 9
#define CPKT_SQLITE_MUTEX_STATIC_APP3 10
#define CPKT_SQLITE_MUTEX_STATIC_LRU 6
#define CPKT_SQLITE_MUTEX_STATIC_LRU2 7
#define CPKT_SQLITE_MUTEX_STATIC_MAIN 2
#define CPKT_SQLITE_MUTEX_STATIC_MASTER 2
#define CPKT_SQLITE_MUTEX_STATIC_MEM 3
#define CPKT_SQLITE_MUTEX_STATIC_MEM2 4
#define CPKT_SQLITE_MUTEX_STATIC_OPEN 4
#define CPKT_SQLITE_MUTEX_STATIC_PMEM 7
#define CPKT_SQLITE_MUTEX_STATIC_PRNG 5
#define CPKT_SQLITE_MUTEX_STATIC_VFS1 11
#define CPKT_SQLITE_MUTEX_STATIC_VFS2 12
#define CPKT_SQLITE_MUTEX_STATIC_VFS3 13
#define CPKT_SQLITE_NOLFS 22
#define CPKT_SQLITE_NOMEM 7
#define CPKT_SQLITE_NOTADB 26
#define CPKT_SQLITE_NOTFOUND 12
#define CPKT_SQLITE_NOTICE 27
#define CPKT_SQLITE_NOTICE_RBU (CPKT_SQLITE_NOTICE | (3 << 8))
#define CPKT_SQLITE_NOTICE_RECOVER_ROLLBACK (CPKT_SQLITE_NOTICE | (2 << 8))
#define CPKT_SQLITE_NOTICE_RECOVER_WAL (CPKT_SQLITE_NOTICE | (1 << 8))
#define CPKT_SQLITE_NULL 5
#define CPKT_SQLITE_OK 0
#define CPKT_SQLITE_OK_LOAD_PERMANENTLY (CPKT_SQLITE_OK | (1 << 8))
#define CPKT_SQLITE_OK_SYMLINK (CPKT_SQLITE_OK | (2 << 8))
#define CPKT_SQLITE_OPEN_AUTOPROXY 0x00000020
#define CPKT_SQLITE_OPEN_CREATE 0x00000004
#define CPKT_SQLITE_OPEN_DELETEONCLOSE 0x00000008
#define CPKT_SQLITE_OPEN_EXCLUSIVE 0x00000010
#define CPKT_SQLITE_OPEN_EXRESCODE 0x02000000
#define CPKT_SQLITE_OPEN_FULLMUTEX 0x00010000
#define CPKT_SQLITE_OPEN_MAIN_DB 0x00000100
#define CPKT_SQLITE_OPEN_MAIN_JOURNAL 0x00000800
#define CPKT_SQLITE_OPEN_MASTER_JOURNAL 0x00004000
#define CPKT_SQLITE_OPEN_MEMORY 0x00000080
#define CPKT_SQLITE_OPEN_NOFOLLOW 0x01000000
#define CPKT_SQLITE_OPEN_NOMUTEX 0x00008000
#define CPKT_SQLITE_OPEN_PRIVATECACHE 0x00040000
#define CPKT_SQLITE_OPEN_READONLY 0x00000001
#define CPKT_SQLITE_OPEN_READWRITE 0x00000002
#define CPKT_SQLITE_OPEN_SHAREDCACHE 0x00020000
#define CPKT_SQLITE_OPEN_SUBJOURNAL 0x00002000
#define CPKT_SQLITE_OPEN_SUPER_JOURNAL 0x00004000
#define CPKT_SQLITE_OPEN_TEMP_DB 0x00000200
#define CPKT_SQLITE_OPEN_TEMP_JOURNAL 0x00001000
#define CPKT_SQLITE_OPEN_TRANSIENT_DB 0x00000400
#define CPKT_SQLITE_OPEN_URI 0x00000040
#define CPKT_SQLITE_OPEN_WAL 0x00080000
#define CPKT_SQLITE_PERM 3
#define CPKT_SQLITE_PRAGMA 19
#define CPKT_SQLITE_PREPARE_DONT_LOG 0x10
#define CPKT_SQLITE_PREPARE_FROM_DDL 0x20
#define CPKT_SQLITE_PREPARE_NORMALIZE 0x02
#define CPKT_SQLITE_PREPARE_NO_VTAB 0x04
#define CPKT_SQLITE_PREPARE_PERSISTENT 0x01
#define CPKT_SQLITE_PROTOCOL 15
#define CPKT_SQLITE_RANGE 25
#define CPKT_SQLITE_READ 20
#define CPKT_SQLITE_READONLY 8
#define CPKT_SQLITE_READONLY_CANTINIT (CPKT_SQLITE_READONLY | (5 << 8))
#define CPKT_SQLITE_READONLY_CANTLOCK (CPKT_SQLITE_READONLY | (2 << 8))
#define CPKT_SQLITE_READONLY_DBMOVED (CPKT_SQLITE_READONLY | (4 << 8))
#define CPKT_SQLITE_READONLY_DIRECTORY (CPKT_SQLITE_READONLY | (6 << 8))
#define CPKT_SQLITE_READONLY_RECOVERY (CPKT_SQLITE_READONLY | (1 << 8))
#define CPKT_SQLITE_READONLY_ROLLBACK (CPKT_SQLITE_READONLY | (3 << 8))
#define CPKT_SQLITE_RECURSIVE 33
#define CPKT_SQLITE_REINDEX 27
#define CPKT_SQLITE_REPLACE 5
#define CPKT_SQLITE_RESULT_SUBTYPE 0x001000000
#define CPKT_SQLITE_ROLLBACK 1
#define CPKT_SQLITE_ROW 100
#define CPKT_SQLITE_SAVEPOINT 32
#define CPKT_SQLITE_SCANSTAT_COMPLEX 0x0001
#define CPKT_SQLITE_SCANSTAT_EST 2
#define CPKT_SQLITE_SCANSTAT_EXPLAIN 4
#define CPKT_SQLITE_SCANSTAT_NAME 3
#define CPKT_SQLITE_SCANSTAT_NCYCLE 7
#define CPKT_SQLITE_SCANSTAT_NLOOP 0
#define CPKT_SQLITE_SCANSTAT_NVISIT 1
#define CPKT_SQLITE_SCANSTAT_PARENTID 6
#define CPKT_SQLITE_SCANSTAT_SELECTID 5
#define CPKT_SQLITE_SCHEMA 17
#define CPKT_SQLITE_SCM_BRANCH "branch-3.53"
#define CPKT_SQLITE_SCM_DATETIME "2026-07-24T19:02:57.525Z"
#define CPKT_SQLITE_SCM_TAGS "release version-3.53.4"
#define CPKT_SQLITE_SELECT 21
#define CPKT_SQLITE_SELFORDER1 0x002000000
#define CPKT_SQLITE_SERIALIZE_NOCOPY 0x001
#define CPKT_SQLITE_SESSION_CONFIG_STRMSIZE 1
#define CPKT_SQLITE_SESSION_OBJCONFIG_ROWID 2
#define CPKT_SQLITE_SESSION_OBJCONFIG_SIZE 1
#define CPKT_SQLITE_SETLK_BLOCK_ON_CONNECT 0x01
#define CPKT_SQLITE_SET_LOCKPROXYFILE CPKT_SQLITE_FCNTL_SET_LOCKPROXYFILE
#define CPKT_SQLITE_SHM_EXCLUSIVE 8
#define CPKT_SQLITE_SHM_LOCK 2
#define CPKT_SQLITE_SHM_NLOCK 8
#define CPKT_SQLITE_SHM_SHARED 4
#define CPKT_SQLITE_SHM_UNLOCK 1
#define CPKT_SQLITE_SOURCE_ID                                                  \
  "2026-07-24 19:02:57 "                                                       \
  "bf7c7f30031888f4e796e429ab3978879485813aaca6f641c7b33e4e09459bcc"
#define CPKT_SQLITE_STATUS_MALLOC_COUNT 9
#define CPKT_SQLITE_STATUS_MALLOC_SIZE 5
#define CPKT_SQLITE_STATUS_MEMORY_USED 0
#define CPKT_SQLITE_STATUS_PAGECACHE_OVERFLOW 2
#define CPKT_SQLITE_STATUS_PAGECACHE_SIZE 7
#define CPKT_SQLITE_STATUS_PAGECACHE_USED 1
#define CPKT_SQLITE_STATUS_PARSER_STACK 6
#define CPKT_SQLITE_STATUS_SCRATCH_OVERFLOW 4
#define CPKT_SQLITE_STATUS_SCRATCH_SIZE 8
#define CPKT_SQLITE_STATUS_SCRATCH_USED 3
#define CPKT_SQLITE_STMTSTATUS_AUTOINDEX 3
#define CPKT_SQLITE_STMTSTATUS_FILTER_HIT 8
#define CPKT_SQLITE_STMTSTATUS_FILTER_MISS 7
#define CPKT_SQLITE_STMTSTATUS_FULLSCAN_STEP 1
#define CPKT_SQLITE_STMTSTATUS_MEMUSED 99
#define CPKT_SQLITE_STMTSTATUS_REPREPARE 5
#define CPKT_SQLITE_STMTSTATUS_RUN 6
#define CPKT_SQLITE_STMTSTATUS_SORT 2
#define CPKT_SQLITE_STMTSTATUS_VM_STEP 4
#define CPKT_SQLITE_SUBTYPE 0x000100000
#define CPKT_SQLITE_SYNC_DATAONLY 0x00010
#define CPKT_SQLITE_SYNC_FULL 0x00003
#define CPKT_SQLITE_SYNC_NORMAL 0x00002
#define CPKT_SQLITE_TEXT 3
#define CPKT_SQLITE_TOOBIG 18
#define CPKT_SQLITE_TRACE_CLOSE 0x08
#define CPKT_SQLITE_TRACE_PROFILE 0x02
#define CPKT_SQLITE_TRACE_ROW 0x04
#define CPKT_SQLITE_TRACE_STMT 0x01
#define CPKT_SQLITE_TRANSACTION 22
#define CPKT_SQLITE_TXN_NONE 0
#define CPKT_SQLITE_TXN_READ 1
#define CPKT_SQLITE_TXN_WRITE 2
#define CPKT_SQLITE_UPDATE 23
#define CPKT_SQLITE_UTF16 4
#define CPKT_SQLITE_UTF16BE 3
#define CPKT_SQLITE_UTF16LE 2
#define CPKT_SQLITE_UTF16_ALIGNED 8
#define CPKT_SQLITE_UTF8 1
#define CPKT_SQLITE_UTF8_ZT 16
#define CPKT_SQLITE_VERSION "3.53.4"
#define CPKT_SQLITE_VERSION_NUMBER 3053004
#define CPKT_SQLITE_VTAB_CONSTRAINT_SUPPORT 1
#define CPKT_SQLITE_VTAB_DIRECTONLY 3
#define CPKT_SQLITE_VTAB_INNOCUOUS 2
#define CPKT_SQLITE_VTAB_USES_ALL_SCHEMAS 4
#define CPKT_SQLITE_WARNING 28
#define CPKT_SQLITE_WARNING_AUTOINDEX (CPKT_SQLITE_WARNING | (1 << 8))

#endif
