set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
include("${CMAKE_CURRENT_LIST_DIR}/cpkt_linux_toolchain_common.cmake")
cpkt_configure_bootlin_toolchain(aarch64-linux-musl)
set(_cpkt_qemu_aarch64 "$ENV{CPKT_QEMU_AARCH64}")
if(NOT _cpkt_qemu_aarch64)
  set(_cpkt_qemu_aarch64 /usr/bin/qemu-aarch64)
endif()
set(CMAKE_CROSSCOMPILING_EMULATOR "${_cpkt_qemu_aarch64};-L;${CMAKE_SYSROOT}" CACHE STRING "" FORCE)
set(CPKT_TARGET_ARCH aarch64 CACHE STRING "" FORCE)
set(CPKT_TARGET_OS linux CACHE STRING "" FORCE)
set(CPKT_TARGET_LIBC musl CACHE STRING "" FORCE)
