set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
include("${CMAKE_CURRENT_LIST_DIR}/cpkt_linux_toolchain_common.cmake")
cpkt_configure_bootlin_toolchain(x86_64-linux-gnu)

get_filename_component(_cpkt_cmake_dir "${CMAKE_CURRENT_LIST_DIR}" DIRECTORY)
get_filename_component(_cpkt_repo_root "${_cpkt_cmake_dir}" DIRECTORY)
set(_cpkt_afl_resolver "${_cpkt_repo_root}/scripts/cpkt-aflpp.sh")
execute_process(
  COMMAND "${_cpkt_afl_resolver}" discover
  RESULT_VARIABLE _cpkt_afl_result
  OUTPUT_VARIABLE _cpkt_afl_description
  ERROR_VARIABLE _cpkt_afl_error)
if(NOT _cpkt_afl_result EQUAL 0)
  message(FATAL_ERROR "Unable to provision pinned AFL++: ${_cpkt_afl_error}")
endif()
foreach(_cpkt_key root cc cxx helper)
  cpkt_toolchain_report_value("${_cpkt_afl_description}" "${_cpkt_key}" "_cpkt_afl_${_cpkt_key}")
endforeach()
foreach(_cpkt_path _cpkt_afl_root _cpkt_afl_cc _cpkt_afl_cxx _cpkt_afl_helper)
  if(NOT EXISTS "${${_cpkt_path}}")
    message(FATAL_ERROR "Pinned AFL++ path is missing: ${${_cpkt_path}}")
  endif()
endforeach()
set(ENV{AFL_PATH} "${_cpkt_afl_helper}")
set(ENV{AFL_CC} "${CMAKE_C_COMPILER}")
set(ENV{AFL_CXX} "${CMAKE_CXX_COMPILER}")
set(CMAKE_C_COMPILER "${_cpkt_afl_cc}" CACHE FILEPATH "Pinned AFL++ GCC wrapper." FORCE)
set(CMAKE_CXX_COMPILER "${_cpkt_afl_cxx}" CACHE FILEPATH "Pinned AFL++ G++ wrapper." FORCE)
set(CPKT_AFLPP_ROOT "${_cpkt_afl_root}" CACHE PATH "Pinned AFL++ GCC-plugin collection." FORCE)
set(CPKT_TARGET_ARCH x86_64 CACHE STRING "" FORCE)
set(CPKT_TARGET_OS linux CACHE STRING "" FORCE)
set(CPKT_TARGET_LIBC gnu CACHE STRING "" FORCE)
