set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
include("${CMAKE_CURRENT_LIST_DIR}/cpkt_linux_toolchain_common.cmake")
cpkt_configure_bootlin_toolchain(armhf-linux-musl)
set(CMAKE_CROSSCOMPILING_EMULATOR /usr/bin/qemu-arm;-L;${CMAKE_SYSROOT} CACHE STRING "" FORCE)
set(CPKT_TARGET_ARCH armhf CACHE STRING "" FORCE)
set(CPKT_TARGET_OS linux CACHE STRING "" FORCE)
set(CPKT_TARGET_LIBC musl CACHE STRING "" FORCE)
