set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
include("${CMAKE_CURRENT_LIST_DIR}/cpkt_linux_toolchain_common.cmake")
cpkt_configure_bootlin_toolchain(armhf-linux-musl)
set(_cpkt_qemu_arm "$ENV{CPKT_QEMU_ARM}")
if(NOT _cpkt_qemu_arm)
  set(_cpkt_qemu_arm /usr/bin/qemu-arm)
endif()
set(CMAKE_CROSSCOMPILING_EMULATOR "${_cpkt_qemu_arm};-L;${CMAKE_SYSROOT}" CACHE STRING "" FORCE)
set(CPKT_TARGET_ARCH armhf CACHE STRING "" FORCE)
set(CPKT_TARGET_OS linux CACHE STRING "" FORCE)
set(CPKT_TARGET_LIBC musl CACHE STRING "" FORCE)
