function(cpkt_llvm_report_value description key out_var)
  string(REGEX MATCH "(^|\n)${key}=([^\r\n]+)" _cpkt_match "${description}")
  if(NOT _cpkt_match)
    message(FATAL_ERROR "Pinned LLVM resolver did not report ${key}")
  endif()
  set(${out_var} "${CMAKE_MATCH_2}" PARENT_SCOPE)
endfunction()

get_filename_component(_cpkt_cmake_dir "${CMAKE_CURRENT_LIST_DIR}" DIRECTORY)
get_filename_component(_cpkt_repo_root "${_cpkt_cmake_dir}" DIRECTORY)
set(_cpkt_llvm_resolver "${_cpkt_repo_root}/scripts/cpkt-llvm.sh")
execute_process(COMMAND "${_cpkt_llvm_resolver}" ensure RESULT_VARIABLE _cpkt_ensure_result ERROR_VARIABLE _cpkt_ensure_error)
if(NOT _cpkt_ensure_result EQUAL 0)
  message(FATAL_ERROR "Unable to install pinned LLVM 22.1.6: ${_cpkt_ensure_error}")
endif()
execute_process(COMMAND "${_cpkt_llvm_resolver}" discover RESULT_VARIABLE _cpkt_discover_result OUTPUT_VARIABLE _cpkt_description ERROR_VARIABLE _cpkt_discover_error)
if(NOT _cpkt_discover_result EQUAL 0)
  message(FATAL_ERROR "Unable to inspect pinned LLVM 22.1.6: ${_cpkt_discover_error}")
endif()
foreach(_cpkt_key root cc cxx ld ar ranlib strip nm objcopy objdump addr2line readelf asan_runtime fuzzer_runtime msan_runtime)
  cpkt_llvm_report_value("${_cpkt_description}" "${_cpkt_key}" "_cpkt_${_cpkt_key}")
endforeach()
foreach(_cpkt_path_key cc cxx ld ar ranlib strip nm objcopy objdump addr2line readelf asan_runtime fuzzer_runtime msan_runtime)
  if(NOT EXISTS "${_cpkt_${_cpkt_path_key}}")
    message(FATAL_ERROR "Pinned LLVM ${_cpkt_path_key} is missing: ${_cpkt_${_cpkt_path_key}}")
  endif()
endforeach()
execute_process(
  COMMAND "${_cpkt_ld}" --version
  RESULT_VARIABLE _cpkt_linker_result
  ERROR_VARIABLE _cpkt_linker_error)
if(NOT _cpkt_linker_result EQUAL 0)
  message(FATAL_ERROR
    "Pinned LLVM linker is not executable: ${_cpkt_ld}. ${_cpkt_linker_error}")
endif()
set(CPKT_TOOLCHAIN_ROOT "${_cpkt_root}" CACHE PATH "Pinned LLVM compiler collection root." FORCE)
set(CPKT_TOOLCHAIN_TARGET llvm-22.1.6 CACHE STRING "Pinned sanitizer compiler collection." FORCE)
set(CMAKE_C_COMPILER "${_cpkt_cc}" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER "${_cpkt_cxx}" CACHE FILEPATH "" FORCE)
set(CMAKE_LINKER "${_cpkt_ld}" CACHE FILEPATH "" FORCE)
set(CMAKE_AR "${_cpkt_ar}" CACHE FILEPATH "" FORCE)
set(CMAKE_RANLIB "${_cpkt_ranlib}" CACHE FILEPATH "" FORCE)
set(CMAKE_STRIP "${_cpkt_strip}" CACHE FILEPATH "" FORCE)
set(CMAKE_NM "${_cpkt_nm}" CACHE FILEPATH "" FORCE)
set(CMAKE_OBJCOPY "${_cpkt_objcopy}" CACHE FILEPATH "" FORCE)
set(CMAKE_OBJDUMP "${_cpkt_objdump}" CACHE FILEPATH "" FORCE)
set(CMAKE_ADDR2LINE "${_cpkt_addr2line}" CACHE FILEPATH "" FORCE)
set(CMAKE_READELF "${_cpkt_readelf}" CACHE FILEPATH "" FORCE)
set(CMAKE_EXE_LINKER_FLAGS_INIT "-fuse-ld=${_cpkt_ld}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-fuse-ld=${_cpkt_ld}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "-fuse-ld=${_cpkt_ld}")
