#!/usr/bin/env python3
"""Generate the strict-C89 public libssh2 facade from pinned headers."""

import argparse
import pathlib
import re
import sys
from typing import Dict, Iterable, List, Tuple


HEADER_NAMES = ("libssh2.h", "libssh2_sftp.h", "libssh2_publickey.h")
REPLACEMENTS: Tuple[Tuple[str, str], ...] = (
    ("ssize_t", "cpkt_libssh2_ssize"),
    ("uint32_t", "cpkt_libssh2_u32"),
    ("uint8_t", "cpkt_libssh2_u8"),
    ("cpkt_libssh2_uint64_t", "cpkt_libssh2_u64"),
    ("cpkt_libssh2_int64_t", "cpkt_libssh2_i64"),
    ("cpkt_libssh2_struct_stat", "cpkt_libssh2_stat"),
    ("struct stat", "cpkt_libssh2_stat"),
    ("cpkt_libssh2_socket_t", "cpkt_libssh2_socket"),
)


def transform(text: str) -> str:
    text = text.replace("LIBSSH2_", "CPKT_LIBSSH2_")
    text = text.replace("libssh2_", "cpkt_libssh2_")
    for native, facade in REPLACEMENTS:
        text = re.sub(r"\b" + re.escape(native) + r"\b", facade, text)
    for upper, lower in (
            ("SESSION", "session"), ("CHANNEL", "channel"),
            ("LISTENER", "listener"), ("KNOWNHOSTS", "knownhosts"),
            ("AGENT", "agent"), ("SFTP_HANDLE", "sftp_handle"),
            ("SFTP_ATTRIBUTES", "sftp_attributes"),
            ("SFTP_STATVFS", "sftp_statvfs_t"), ("SFTP", "sftp"),
            ("PUBLICKEY", "publickey")):
        text = re.sub(r"\bCPKT_LIBSSH2_" + upper + r"\b",
                      "cpkt_libssh2_" + lower, text)
    return text


def trim_header(text: str, name: str) -> str:
    if name == "libssh2.h":
        start = text.find("/* Part of every banner")
        end = text.rfind("#ifdef __cplusplus")
    elif name == "libssh2_sftp.h":
        start = text.find("#define LIBSSH2_SFTP_VERSION")
        end = text.rfind("#ifdef __cplusplus")
    else:
        start = text.find("typedef struct _LIBSSH2_PUBLICKEY")
        end = text.rfind("#ifdef __cplusplus")
    if start < 0 or end < 0:
        raise ValueError("unable to locate public body in " + name)
    return text[start:end]


def strip_redeclared_types(body: str) -> str:
    names = (
        "LIBSSH2_SESSION", "LIBSSH2_CHANNEL", "LIBSSH2_LISTENER",
        "LIBSSH2_KNOWNHOSTS", "LIBSSH2_AGENT", "LIBSSH2_SFTP",
        "LIBSSH2_SFTP_HANDLE", "LIBSSH2_SFTP_ATTRIBUTES",
        "LIBSSH2_SFTP_STATVFS", "LIBSSH2_PUBLICKEY",
    )
    for name in names:
        body = re.sub(
            r"typedef struct _" + name + r"\s+" + name + r"\s*;\s*",
            "", body)
    for name in ("_LIBSSH2_SFTP_ATTRIBUTES", "_LIBSSH2_SFTP_STATVFS"):
        body = re.sub(
            r"struct " + name + r"\s*\{.*?\}\s*;\s*",
            "", body, flags=re.DOTALL)
    return body


def public_header(headers: Dict[str, str]) -> str:
    body = "\n".join(
        transform(strip_redeclared_types(trim_header(headers[name], name)))
        for name in HEADER_NAMES)
    return """/* Generated by tools/generate_libssh2_c89_facade.py; do not edit. */
#ifndef CPKT_LIBSSH2_H
#define CPKT_LIBSSH2_H

#include <stddef.h>
#include <stdio.h>
#include <time.h>
#include <string.h>

#if defined(_WIN32) && defined(CPKT_LIBSSH2_BUILDING_SHARED)
#define CPKT_LIBSSH2_API __declspec(dllexport)
#elif defined(_WIN32) && !defined(CPKT_LIBSSH2_STATIC)
#define CPKT_LIBSSH2_API __declspec(dllimport)
#elif defined(__GNUC__) || defined(__clang__)
#define CPKT_LIBSSH2_API __attribute__((visibility("default")))
#else
#define CPKT_LIBSSH2_API
#endif
#define CPKT_LIBSSH2_DEPRECATED(version, message)

#ifdef __cplusplus
extern "C" {
#endif

typedef signed char cpkt_libssh2_i8;
typedef unsigned char cpkt_libssh2_u8;
typedef unsigned int cpkt_libssh2_u32;
typedef ptrdiff_t cpkt_libssh2_ssize;
typedef int cpkt_libssh2_socket;
typedef struct cpkt_libssh2_u64 {
  unsigned long high;
  unsigned long low;
} cpkt_libssh2_u64;
typedef cpkt_libssh2_u64 cpkt_libssh2_i64;

typedef struct cpkt_libssh2_session cpkt_libssh2_session;
typedef struct cpkt_libssh2_channel cpkt_libssh2_channel;
typedef struct cpkt_libssh2_listener cpkt_libssh2_listener;
typedef struct cpkt_libssh2_knownhosts cpkt_libssh2_knownhosts;
typedef struct cpkt_libssh2_agent cpkt_libssh2_agent;
typedef struct cpkt_libssh2_sftp cpkt_libssh2_sftp;
typedef struct cpkt_libssh2_sftp_handle cpkt_libssh2_sftp_handle;
typedef struct cpkt_libssh2_publickey cpkt_libssh2_publickey;

typedef struct cpkt_libssh2_sftp_attributes {
  unsigned long flags;
  cpkt_libssh2_u64 filesize;
  unsigned long uid;
  unsigned long gid;
  unsigned long permissions;
  unsigned long atime;
  unsigned long mtime;
} cpkt_libssh2_sftp_attributes;

typedef struct cpkt_libssh2_sftp_statvfs {
  cpkt_libssh2_u64 f_bsize;
  cpkt_libssh2_u64 f_frsize;
  cpkt_libssh2_u64 f_blocks;
  cpkt_libssh2_u64 f_bfree;
  cpkt_libssh2_u64 f_bavail;
  cpkt_libssh2_u64 f_files;
  cpkt_libssh2_u64 f_ffree;
  cpkt_libssh2_u64 f_favail;
  cpkt_libssh2_u64 f_fsid;
  cpkt_libssh2_u64 f_flag;
  cpkt_libssh2_u64 f_namemax;
} cpkt_libssh2_sftp_statvfs_t;

typedef struct cpkt_libssh2_stat {
  cpkt_libssh2_u64 size;
  unsigned long mode;
  unsigned long uid;
  unsigned long gid;
  long mtime;
  long atime;
} cpkt_libssh2_stat;

{body}

#ifdef __cplusplus
}
#endif

#endif /* CPKT_LIBSSH2_H */
""".replace("{body}", body)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--include-dir", required=True, type=pathlib.Path)
    parser.add_argument("--header", required=True, type=pathlib.Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    include_dirs = [pathlib.Path(value) for value in
                    str(args.include_dir).split(";") if value]
    header_dir = next(
        (value for value in include_dirs if (value / "libssh2.h").is_file()),
        None)
    if header_dir is None:
        raise ValueError("libssh2.h is absent from include directories: " +
                         str(args.include_dir))
    headers = {}
    for name in HEADER_NAMES:
        path = header_dir / name
        if not path.is_file():
            raise ValueError("required input is missing: " + str(path))
        headers[name] = path.read_text(encoding="utf-8")
    args.header.parent.mkdir(parents=True, exist_ok=True)
    args.header.write_text(public_header(headers), encoding="utf-8")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError) as error:
        print("generate_libssh2_c89_facade.py: " + str(error), file=sys.stderr)
        raise SystemExit(1)
