if(NOT DEFINED CPKT_KRB5_BUILD_DIR OR NOT IS_DIRECTORY "${CPKT_KRB5_BUILD_DIR}")
  message(FATAL_ERROR "CPKT_KRB5_BUILD_DIR must name a configured Kerberos build")
endif()

set(_header "${CPKT_KRB5_BUILD_DIR}/include/autoconf.h")
set(_log "${CPKT_KRB5_BUILD_DIR}/config.log")
foreach(_path IN ITEMS "${_header}" "${_log}")
  if(NOT EXISTS "${_path}")
    message(FATAL_ERROR "Kerberos configure did not produce ${_path}")
  endif()
endforeach()

file(STRINGS "${_header}" _tls REGEX "^#define TLS_IMPL_OPENSSL 1$")
if(NOT _tls)
  message(FATAL_ERROR "Kerberos configured without bundled OpenSSL TLS support")
endif()

if(CPKT_KRB5_REQUIRE_GLIBC_REENTRANT STREQUAL "gnu")
  foreach(_function IN ITEMS getpwnam_r getpwuid_r gethostbyname_r getservbyname_r gmtime_r localtime_r)
    file(STRINGS "${_log}" _result REGEX "^ac_cv_func_${_function}=yes$")
    if(NOT _result)
      message(FATAL_ERROR "Kerberos configure disabled ${_function} on glibc")
    endif()
  endforeach()
endif()
