if(NOT DEFINED CPKT_AUTOTOOLS_LIBRARY_SOURCE_DIR)
  message(FATAL_ERROR "CPKT_AUTOTOOLS_LIBRARY_SOURCE_DIR is required")
endif()
if(NOT DEFINED CPKT_AUTOTOOLS_LIBRARY_DESTINATION_DIR)
  message(FATAL_ERROR "CPKT_AUTOTOOLS_LIBRARY_DESTINATION_DIR is required")
endif()
if(NOT DEFINED CPKT_AUTOTOOLS_LIBRARY_BASENAME)
  message(FATAL_ERROR "CPKT_AUTOTOOLS_LIBRARY_BASENAME is required")
endif()

file(GLOB library_artifacts
  "${CPKT_AUTOTOOLS_LIBRARY_SOURCE_DIR}/${CPKT_AUTOTOOLS_LIBRARY_BASENAME}.*")
if(NOT library_artifacts)
  message(FATAL_ERROR
    "No ${CPKT_AUTOTOOLS_LIBRARY_BASENAME} artifacts in ${CPKT_AUTOTOOLS_LIBRARY_SOURCE_DIR}")
endif()

file(MAKE_DIRECTORY "${CPKT_AUTOTOOLS_LIBRARY_DESTINATION_DIR}")
foreach(library_artifact IN LISTS library_artifacts)
  if(NOT library_artifact MATCHES "\\.la(i)?$")
    file(COPY "${library_artifact}"
      DESTINATION "${CPKT_AUTOTOOLS_LIBRARY_DESTINATION_DIR}")
  endif()
endforeach()
