include("${CMAKE_CURRENT_LIST_DIR}/CpktReadOnlyToolchain.cmake")
execute_process(COMMAND python3 "${CMAKE_CURRENT_LIST_DIR}/../scripts/cpkt_afl_discover.py"
  OUTPUT_VARIABLE _description RESULT_VARIABLE _status)
if(NOT _status EQUAL 0)
  message(FATAL_ERROR "Pinned AFL tooling is absent; prepare it explicitly before selected hardening")
endif()
foreach(_key root cc cxx helper)
  cpkt_toolchain_report_value("${_description}" "${_key}" "_afl_${_key}")
endforeach()
set(ENV{AFL_PATH} "${_afl_helper}")
set(ENV{AFL_CC} "${CMAKE_C_COMPILER}")
set(ENV{AFL_CXX} "${CMAKE_CXX_COMPILER}")
set(CMAKE_C_COMPILER "${_afl_cc}" CACHE FILEPATH "Pinned AFL GCC wrapper." FORCE)
set(CMAKE_CXX_COMPILER "${_afl_cxx}" CACHE FILEPATH "Pinned AFL C++ wrapper." FORCE)
set(CPKT_AFLPP_ROOT "${_afl_root}" CACHE PATH "Pinned AFL collection." FORCE)
