# Ownership comes exclusively from components.json. Registration wrappers reject
# omissions; they never create targets/tests belonging to an unselected group.
file(READ "${CMAKE_SOURCE_DIR}/cmake/components.json" CPKT_INVENTORY)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
  "${CMAKE_SOURCE_DIR}/cmake/components.json")
set(CPKT_GROUP "$ENV{GROUP}" CACHE STRING "Selected package: core, db, misc, all.")
if(CPKT_GROUP STREQUAL "")
  set(CPKT_GROUP all CACHE STRING "Selected package." FORCE)
endif()
if(NOT CPKT_GROUP MATCHES "^(core|db|misc|all)$")
  message(FATAL_ERROR "Unknown CPKT_GROUP=${CPKT_GROUP}")
endif()
foreach(_group core db misc)
  set(CPKT_SELECT_${_group} OFF)
  if(CPKT_GROUP STREQUAL "all" OR CPKT_GROUP STREQUAL "${_group}")
    set(CPKT_SELECT_${_group} ON)
  endif()
endforeach()

# Parse JSON once per record. Expanded loop names use the most specific
# template, then cache their resolved owner/key for subsequent operations.
foreach(_kind targets tests)
  string(JSON _count LENGTH "${CPKT_INVENTORY}" "${_kind}")
  math(EXPR _last "${_count} - 1")
  set(_templates "")
  foreach(_index RANGE 0 ${_last})
    string(JSON _name MEMBER "${CPKT_INVENTORY}" "${_kind}" ${_index})
    string(JSON _owner GET "${CPKT_INVENTORY}" "${_kind}" "${_name}" group)
    set_property(GLOBAL PROPERTY "CPKT_OWNER_${_kind}_${_name}" "${_owner}")
    set_property(GLOBAL PROPERTY "CPKT_KEY_${_kind}_${_name}" "${_name}")
    if(_name MATCHES "\\$\\{")
      list(APPEND _templates "${_name}")
      string(REGEX REPLACE "\\$\\{[^}]+\\}" "[A-Za-z0-9_-]+" _pattern "${_name}")
      string(REGEX REPLACE "\\$\\{[^}]+\\}" "" _literal "${_name}")
      string(LENGTH "${_literal}" _length)
      set_property(GLOBAL PROPERTY "CPKT_PATTERN_${_kind}_${_name}" "${_pattern}")
      set_property(GLOBAL PROPERTY "CPKT_SPECIFICITY_${_kind}_${_name}" "${_length}")
    endif()
  endforeach()
  set_property(GLOBAL PROPERTY "CPKT_TEMPLATES_${_kind}" "${_templates}")
endforeach()

function(cpkt_inventory_owner kind name output)
  get_property(_owner GLOBAL PROPERTY "CPKT_OWNER_${kind}_${name}")
  if(NOT _owner)
    get_property(_templates GLOBAL PROPERTY "CPKT_TEMPLATES_${kind}")
    set(_specificity -1)
    foreach(_template IN LISTS _templates)
      get_property(_pattern GLOBAL PROPERTY "CPKT_PATTERN_${kind}_${_template}")
      if("${name}" MATCHES "^${_pattern}$")
        get_property(_length GLOBAL PROPERTY "CPKT_SPECIFICITY_${kind}_${_template}")
        if(_length EQUAL _specificity)
          message(FATAL_ERROR "Ambiguous inventory ownership: ${kind}/${name}")
        elseif(_length GREATER _specificity)
          get_property(_owner GLOBAL PROPERTY "CPKT_OWNER_${kind}_${_template}")
          set(_key "${_template}")
          set(_specificity "${_length}")
        endif()
      endif()
    endforeach()
    if(_owner)
      set_property(GLOBAL PROPERTY "CPKT_OWNER_${kind}_${name}" "${_owner}")
      set_property(GLOBAL PROPERTY "CPKT_KEY_${kind}_${name}" "${_key}")
    endif()
  endif()
  if(NOT _owner)
    message(FATAL_ERROR "Missing inventory ownership: ${kind}/${name}; update cmake/components.json")
  endif()
  set(${output} "${_owner}" PARENT_SCOPE)
endfunction()

function(cpkt_inventory_selected kind name output)
  cpkt_inventory_owner("${kind}" "${name}" _owner)
  set(_selected OFF)
  if((CPKT_GROUP STREQUAL "all" AND NOT CPKT_COMPOSITION_ONLY) OR CPKT_GROUP STREQUAL "${_owner}"
      OR (CPKT_COMPOSITION_ONLY AND _owner MATCHES "^(all|tooling)$"))
    set(_selected ON)
  endif()
  set(${output} "${_selected}" PARENT_SCOPE)
endfunction()

function(cpkt_group_add_library name)
  cpkt_inventory_selected(targets "${name}" _selected)
  if(_selected)
    add_library(${name} ${ARGN})
  endif()
endfunction()
function(cpkt_group_add_executable name)
  cpkt_inventory_selected(targets "${name}" _selected)
  if(_selected)
    add_executable(${name} ${ARGN})
  endif()
endfunction()
function(cpkt_group_add_custom_target name)
  cpkt_inventory_selected(targets "${name}" _selected)
  if(_selected)
    add_custom_target(${name} ${ARGN})
  endif()
endfunction()
function(cpkt_group_add_test)
  cmake_parse_arguments(PARSE_ARGV 0 _test "" "NAME;WORKING_DIRECTORY" "COMMAND;CONFIGURATIONS")
  cpkt_inventory_selected(tests "${_test_NAME}" _selected)
  if(_selected)
    get_property(_key GLOBAL PROPERTY "CPKT_KEY_tests_${_test_NAME}")
    string(JSON _preflight ERROR_VARIABLE _missing GET "${CPKT_INVENTORY}" tests "${_key}" preflight)
    if(NOT _missing AND _preflight)
      add_test(NAME "${_test_NAME}" COMMAND "${CPKT_OPERATION_PYTHON}"
        "${CMAKE_SOURCE_DIR}/scripts/cpkt_helper_dispatch.py" --root "${CMAKE_SOURCE_DIR}"
        --group "${CPKT_GROUP}" --target "${CPKT_TARGET_ID}" --test "${_test_NAME}"
        --binary "${CMAKE_BINARY_DIR}" -- ${_test_COMMAND})
    else()
      add_test(${ARGV})
    endif()
    cpkt_inventory_owner(tests "${_test_NAME}" _owner)
    set_property(TEST "${_test_NAME}" APPEND PROPERTY LABELS "group:${_owner}")
  endif()
endfunction()
function(cpkt_group_set_tests_properties)
  set(_tests "")
  set(_properties "")
  set(_in_properties OFF)
  math(EXPR _last "${ARGC} - 1")
  foreach(_index RANGE 0 ${_last})
    set(_argument "${ARGV${_index}}")
    if(_argument STREQUAL "PROPERTIES")
      set(_in_properties ON)
    elseif(_in_properties)
      string(APPEND _properties " [==[${_argument}]==]")
    else()
      cpkt_inventory_selected(tests "${_argument}" _selected)
      if(_selected)
        if(NOT TEST "${_argument}")
          message(FATAL_ERROR "Required selected test is missing: ${_argument}")
        endif()
        list(APPEND _tests "${_argument}")
      endif()
    endif()
  endforeach()
  if(_tests)
    string(REPLACE ";" " " _test_arguments "${_tests}")
    cmake_language(EVAL CODE "set_tests_properties(${_test_arguments} PROPERTIES ${_properties})")
    foreach(_test IN LISTS _tests)
      cpkt_inventory_owner(tests "${_test}" _owner)
      set_property(TEST "${_test}" APPEND PROPERTY LABELS "group:${_owner}")
    endforeach()
  endif()
endfunction()

function(cpkt_group_set_property)
  if("${ARGV0}" STREQUAL "TEST")
    cpkt_inventory_selected(tests "${ARGV1}" _selected)
    if(_selected)
      set_property(${ARGV})
    endif()
  else()
    set_property(${ARGV})
  endif()
endfunction()

# Keep target operations explicit. A selected missing target is an error; only
# commands for inventory-owned unselected targets may be suppressed.
function(cpkt_group_target_command command name)
  if(CPKT_COMPOSITION_ONLY)
    cpkt_inventory_selected(targets "${name}" _selected)
    if(NOT _selected)
      return()
    endif()
  endif()
  if(TARGET "${name}")
    cmake_language(CALL "${command}" "${name}" ${ARGN})
  else()
    cpkt_inventory_selected(targets "${name}" _selected)
    if(_selected)
      message(FATAL_ERROR "Required selected target is missing: ${name}")
    endif()
  endif()
endfunction()
function(cpkt_group_set_target_properties)
  set(_targets "")
  set(_properties "")
  set(_in_properties OFF)
  math(EXPR _last "${ARGC} - 1")
  foreach(_index RANGE 0 ${_last})
    set(_argument "${ARGV${_index}}")
    if(_argument STREQUAL "PROPERTIES")
      set(_in_properties ON)
    elseif(_in_properties)
      string(APPEND _properties " [==[${_argument}]==]")
    elseif(TARGET "${_argument}")
      if(CPKT_COMPOSITION_ONLY)
        cpkt_inventory_selected(targets "${_argument}" _selected)
      else()
        set(_selected ON)
      endif()
      if(_selected)
        list(APPEND _targets "${_argument}")
      endif()
    else()
      cpkt_inventory_selected(targets "${_argument}" _selected)
      if(_selected)
        message(FATAL_ERROR "Required selected target is missing: ${_argument}")
      endif()
    endif()
  endforeach()
  if(_targets)
    string(REPLACE ";" " " _target_arguments "${_targets}")
    cmake_language(EVAL CODE "set_target_properties(${_target_arguments} PROPERTIES ${_properties})")
  endif()
endfunction()
function(cpkt_group_use_local_runtime name)
  if(TARGET "${name}")
    cpkt_use_local_runtime("${name}" ${ARGN})
  endif()
endfunction()
function(cpkt_group_get_target_property output name property)
  if(TARGET "${name}")
    get_target_property(_value "${name}" "${property}")
    set(${output} "${_value}" PARENT_SCOPE)
  endif()
endfunction()

function(cpkt_validate_owned_graph)
  get_property(_targets DIRECTORY PROPERTY BUILDSYSTEM_TARGETS)
  if(NOT CPKT_FACADE_ONLY)
    string(JSON _count LENGTH "${CPKT_INVENTORY}" targets)
    if(_count GREATER 0)
      math(EXPR _last "${_count} - 1")
      foreach(_index RANGE 0 ${_last})
        string(JSON _name MEMBER "${CPKT_INVENTORY}" targets ${_index})
        string(JSON _public GET "${CPKT_INVENTORY}" targets "${_name}" public)
        string(JSON _owner GET "${CPKT_INVENTORY}" targets "${_name}" group)
        if(_public AND (CPKT_GROUP STREQUAL "all" OR CPKT_GROUP STREQUAL _owner))
          string(JSON _names ERROR_VARIABLE _missing GET "${CPKT_INVENTORY}" targets "${_name}" names)
          if(_missing)
            set(_required_names "${_name}")
          else()
            string(JSON _length LENGTH "${_names}")
            math(EXPR _end "${_length} - 1")
            set(_required_names "")
            foreach(_entry RANGE 0 ${_end})
              string(JSON _required GET "${_names}" ${_entry})
              list(APPEND _required_names "${_required}")
            endforeach()
          endif()
          foreach(_required IN LISTS _required_names)
            if(NOT TARGET "${_required}")
              message(FATAL_ERROR "Missing required public inventory target: ${_required}")
            endif()
          endforeach()
        endif()
      endforeach()
    endif()
  endif()
  set(_outputs "")
  set(_facades "")
  foreach(_target IN LISTS _targets)
    if(_target STREQUAL "cpkt_operation_guard")
      continue()
    endif()
    if(_target STREQUAL "cpkt_deps_all")
      continue()
    endif()
    cpkt_inventory_owner(targets "${_target}" _owner)
    foreach(_property LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
      get_target_property(_links "${_target}" "${_property}")
      foreach(_link IN LISTS _links)
        if(_link MATCHES "cmocka" AND NOT _target MATCHES "^cpkt_cmocka")
          get_property(_key GLOBAL PROPERTY "CPKT_KEY_targets_${_target}")
          string(JSON _public GET "${CPKT_INVENTORY}" targets "${_key}" public)
          if(_public)
            message(FATAL_ERROR "Production facade ${_target} links cmocka: ${_link}")
          endif()
        endif()
        if(TARGET "${_link}" AND _link MATCHES "^cpkt_" AND NOT _link STREQUAL "cpkt_operation_guard")
          cpkt_inventory_owner(targets "${_link}" _linked_owner)
          if((_owner STREQUAL "core" AND _linked_owner MATCHES "^(db|misc)$") OR
              (_owner STREQUAL "db" AND _linked_owner STREQUAL "misc") OR
              (_owner STREQUAL "misc" AND _linked_owner STREQUAL "db"))
            message(FATAL_ERROR "Forbidden group linkage: ${_target} -> ${_link}")
          endif()
        endif()
      endforeach()
    endforeach()
    get_target_property(_type "${_target}" TYPE)
    if(_type MATCHES "^(STATIC_LIBRARY|SHARED_LIBRARY)$")
      get_property(_key GLOBAL PROPERTY "CPKT_KEY_targets_${_target}")
      string(JSON _public GET "${CPKT_INVENTORY}" targets "${_key}" public)
      string(JSON _composition_input ERROR_VARIABLE _missing GET
        "${CPKT_INVENTORY}" targets "${_key}" composition_input)
      if(_public OR (NOT _missing AND _composition_input))
        list(APPEND _facades "${_target}")
      endif()
    endif()
    add_dependencies("${_target}" cpkt_operation_guard)
    if(_type MATCHES "^(EXECUTABLE|STATIC_LIBRARY|SHARED_LIBRARY|MODULE_LIBRARY)$")
      string(APPEND _outputs "$<TARGET_FILE:${_target}>\n")
    endif()
    if(_type MATCHES "^(STATIC_LIBRARY|SHARED_LIBRARY)$")
      string(APPEND _outputs "$<TARGET_LINKER_FILE:${_target}>\n")
      if(_type STREQUAL "SHARED_LIBRARY")
        string(APPEND _outputs "$<TARGET_SONAME_FILE:${_target}>\n")
      endif()
    endif()
  endforeach()
  if(_facades)
    export(TARGETS ${_facades} FILE "${CMAKE_BINARY_DIR}/cpkt-facades.cmake")
  endif()
  file(GENERATE OUTPUT "${CMAKE_BINARY_DIR}/cpkt-owned-outputs.txt" CONTENT "${_outputs}")
  if(CPKT_BUILD_TESTS)
    set(_coverage_arguments "")
    if(CPKT_COMPOSITION_ONLY)
      list(APPEND _coverage_arguments --composition)
    elseif(CPKT_FACADE_ONLY AND CPKT_ENABLE_FUZZING AND CPKT_GROUP STREQUAL "core")
      list(APPEND _coverage_arguments --profile lua-fuzz)
    endif()
    execute_process(COMMAND "${CPKT_OPERATION_PYTHON}" "${CMAKE_SOURCE_DIR}/scripts/cpkt_expected_tests.py"
      --root "${CMAKE_SOURCE_DIR}" --group "${CPKT_GROUP}"
      --output "${CMAKE_BINARY_DIR}/cpkt-required-tests.cmake" ${_coverage_arguments}
      RESULT_VARIABLE _coverage_status)
    if(NOT _coverage_status EQUAL 0)
      message(FATAL_ERROR "Cannot resolve required inventory coverage")
    endif()
    cmake_language(DEFER CALL include "${CMAKE_BINARY_DIR}/cpkt-required-tests.cmake")
  endif()
  get_property(_tests DIRECTORY PROPERTY TESTS)
  foreach(_test IN LISTS _tests)
    cpkt_inventory_owner(tests "${_test}" _owner)
    get_test_property("${_test}" DISABLED _disabled)
    if(_disabled)
      message(FATAL_ERROR "Required test disabled: ${_test}")
    endif()
  endforeach()
endfunction()
