# Core provisions explicitly before configuration. Optional graphs only discover.
set(_target "$ENV{CPKT_RESOLVED_TARGET}")
if(NOT _target MATCHES "^(x86_64|aarch64|armhf)-linux-(gnu|musl)$")
  message(FATAL_ERROR "Discovery-only Linux toolchain needs CPKT_RESOLVED_TARGET")
endif()
set(CMAKE_SYSTEM_NAME Linux)
string(REGEX REPLACE "-linux-.*" "" _arch "${_target}")
set(CMAKE_SYSTEM_PROCESSOR "${_arch}")
if(_arch STREQUAL "armhf")
  set(CMAKE_SYSTEM_PROCESSOR arm)
endif()
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
include("${CMAKE_CURRENT_LIST_DIR}/CpktToolchainDiscovery.cmake")
cpkt_discover_bootlin_toolchain("${_target}")
if(_arch STREQUAL "aarch64")
  set(_runner "$ENV{CPKT_QEMU_AARCH64}")
  if(NOT _runner)
    set(_runner /usr/bin/qemu-aarch64)
  endif()
elseif(_arch STREQUAL "armhf")
  set(_runner "$ENV{CPKT_QEMU_ARM}")
  if(NOT _runner)
    set(_runner /usr/bin/qemu-arm)
  endif()
endif()
if(_runner)
  if(NOT EXISTS "${_runner}")
    message(FATAL_ERROR "Required selected runtime runner is missing: ${_runner}")
  endif()
  set(CMAKE_CROSSCOMPILING_EMULATOR "${_runner};-L;${CMAKE_SYSROOT}" CACHE STRING "" FORCE)
endif()
set(CPKT_TARGET_ARCH "${_arch}" CACHE STRING "" FORCE)
set(CPKT_TARGET_OS linux CACHE STRING "" FORCE)
string(REGEX REPLACE ".*-linux-" "" _libc "${_target}")
set(CPKT_TARGET_LIBC "${_libc}" CACHE STRING "" FORCE)
