# Each configure revalidates bytes. Only exact closure successes within this
# configure are cached; CMake cache entries cannot supply cross-operation proof.
function(cpkt_sdk_validate group)
  get_filename_component(prefix "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../../.." REALPATH)
  set(_cpkt_sdk_prefix "${prefix}" PARENT_SCOPE)
  set(groups core)
  if(NOT group STREQUAL "core")
    list(APPEND groups "${group}")
  endif()
  set(expectations "")
  foreach(pair IN ITEMS "CPKT_TARGET_ID|target" "CPKT_TARGET_ARCH|arch" "CPKT_TARGET_OS|os" "CPKT_TARGET_LIBC|libc" "CMAKE_SYSTEM_NAME|system" "CMAKE_SYSTEM_PROCESSOR|cpu")
    string(REPLACE "|" ";" pair "${pair}")
    list(GET pair 0 variable)
    list(GET pair 1 argument)
    if(DEFINED ${variable} AND NOT "${${variable}}" STREQUAL "")
      list(APPEND expectations "--${argument}" "${${variable}}")
    endif()
  endforeach()
  foreach(architecture IN LISTS CMAKE_OSX_ARCHITECTURES)
    list(APPEND expectations --cpu "${architecture}")
  endforeach()
  set(identity "${prefix};${expectations}")
  foreach(selected IN LISTS groups)
    set(manifest "${prefix}/share/c.pkt.systems/packages/${selected}.json")
    if(NOT EXISTS "${manifest}")
      message(FATAL_ERROR "Missing ${selected} package manifest in ${prefix}")
    endif()
    file(READ "${manifest}" content)
    string(JSON id ERROR_VARIABLE error GET "${content}" package_id)
    if(error)
      message(FATAL_ERROR "Malformed ${selected} package manifest: ${error}")
    endif()
    string(APPEND identity ";${selected}=${id}")
  endforeach()
  string(SHA256 key "${identity}")
  set(_cpkt_sdk_key "${key}" PARENT_SCOPE)
  get_property(valid GLOBAL PROPERTY "CPKT_VALIDATED_${key}")
  if(NOT valid)
    # The validator is a host program; package lookup isolation remains intact.
    set(CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH TRUE)
    set(CMAKE_FIND_USE_CMAKE_SYSTEM_PATH TRUE)
    find_program(python NAMES python3 NO_CMAKE_FIND_ROOT_PATH REQUIRED)
    list(JOIN groups "," selection)
    execute_process(COMMAND "${python}" "${prefix}/share/c.pkt.systems/validate-sdk.py"
      --prefix "${prefix}" --groups "${selection}" --cmake-summary ${expectations}
      RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT status EQUAL 0)
      message(FATAL_ERROR "SDK validation before imports failed: ${error}")
    endif()
    string(JSON libraries GET "${output}" library_names)
    set_property(GLOBAL PROPERTY "CPKT_LIBRARY_NAMES_${key}" "${libraries}")
    set_property(GLOBAL PROPERTY "CPKT_VALIDATED_${key}" TRUE)
  endif()
endfunction()

# Imported GLOBAL targets created in a sibling directory are visible to this
# consumer, but CMake lists them only in their defining directory.
function(cpkt_sdk_global_imports directory output)
  get_property(imports DIRECTORY "${directory}" PROPERTY IMPORTED_TARGETS)
  set(result "")
  foreach(target IN LISTS imports)
    if(TARGET "${target}")
      get_target_property(is_global "${target}" IMPORTED_GLOBAL)
      if(is_global)
        list(APPEND result "${target}")
      endif()
    endif()
  endforeach()
  get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
  foreach(child IN LISTS children)
    cpkt_sdk_global_imports("${child}" nested)
    list(APPEND result ${nested})
  endforeach()
  set(${output} "${result}" PARENT_SCOPE)
endfunction()

# Reject pre-existing host imports of libraries in the selected SDK closure.
function(cpkt_sdk_assert_targets group)
  get_filename_component(prefix "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../../.." REALPATH)
  cpkt_sdk_validate("${group}")
  get_property(libraries GLOBAL PROPERTY "CPKT_LIBRARY_NAMES_${_cpkt_sdk_key}")
  set(directory "${CMAKE_CURRENT_SOURCE_DIR}")
  set(imports "")
  while(directory)
    get_property(targets DIRECTORY "${directory}" PROPERTY IMPORTED_TARGETS)
    list(APPEND imports ${targets})
    get_property(directory DIRECTORY "${directory}" PROPERTY PARENT_DIRECTORY)
  endwhile()
  cpkt_sdk_global_imports("${CMAKE_SOURCE_DIR}" global_imports)
  list(APPEND imports ${global_imports})
  list(REMOVE_DUPLICATES imports)
  foreach(target IN LISTS imports)
      get_target_property(configurations "${target}" IMPORTED_CONFIGURATIONS)
      set(properties IMPORTED_LOCATION IMPORTED_IMPLIB INTERFACE_LINK_LIBRARIES)
      foreach(configuration IN LISTS configurations)
        string(TOUPPER "${configuration}" configuration)
        list(APPEND properties "IMPORTED_LOCATION_${configuration}" "IMPORTED_IMPLIB_${configuration}")
      endforeach()
      foreach(property IN LISTS properties)
        get_target_property(location "${target}" "${property}")
        set(locations "")
        foreach(value IN LISTS location)
          if(IS_ABSOLUTE "${value}")
            # A literal comma belongs to a normal path, not a genex delimiter.
            list(APPEND locations "${value}")
          else()
            string(REGEX MATCHALL "/[^;,<>]+" generated_locations "${value}")
            list(APPEND locations ${generated_locations})
          endif()
        endforeach()
        foreach(location IN LISTS locations)
          get_filename_component(name "${location}" NAME)
          if(name IN_LIST libraries)
            file(RELATIVE_PATH relative "${prefix}" "${location}")
            if(relative MATCHES "^[.][.]/" OR IS_ABSOLUTE "${relative}")
              message(FATAL_ERROR "Existing target ${target} imports SDK library ${name} from outside validated prefix: ${location}")
            endif()
          endif()
        endforeach()
      endforeach()
  endforeach()
endfunction()
