# An all-group composition graph compiles only all-owned consumers/tooling.
# Group facades remain in their Debug/Release graphs and are imported here.
foreach(_group core db misc)
  set(_graph "${CMAKE_SOURCE_DIR}/build/${CPKT_TARGET_ID}/${_group}/${CMAKE_BUILD_TYPE}")
  if(NOT EXISTS "${_graph}/cpkt-facades.cmake")
    message(FATAL_ERROR "Missing prepared ${_group} facade graph: ${_graph}")
  endif()
  include("${_graph}/cpkt-facades.cmake")
  foreach(_facade nghttp2 libssh2 mqttc lua)
    if(_group STREQUAL "core")
      string(TOUPPER "${_facade}" _variable)
      set(CPKT_${_variable}_FACADE_INCLUDE_DIR "${_graph}/generated/${_facade}/include")
      set(CPKT_${_variable}_FACADE_HEADER "${_graph}/generated/${_facade}/include/cpkt/${_facade}.h")
      set(CPKT_${_variable}_FACADE_SOURCE "${_graph}/generated/${_facade}/src/${_facade}.c")
    endif()
  endforeach()
  if(_group STREQUAL "misc")
    set(CPKT_OPCUA_GENERATED_DIR "${_graph}/generated/opcua")
  endif()
endforeach()
add_custom_target(cpkt_deps_all)
