if(NOT DEFINED CPKT_CYRUS_SASL_BUILD_DIR)
  message(FATAL_ERROR "CPKT_CYRUS_SASL_BUILD_DIR is required")
endif()

set(_config "${CPKT_CYRUS_SASL_BUILD_DIR}/config.h")
set(_lib_makefile "${CPKT_CYRUS_SASL_BUILD_DIR}/lib/Makefile")
set(_plugins_makefile "${CPKT_CYRUS_SASL_BUILD_DIR}/plugins/Makefile")
foreach(_required IN ITEMS "${_config}" "${_lib_makefile}" "${_plugins_makefile}")
  if(NOT EXISTS "${_required}")
    message(FATAL_ERROR "Cyrus SASL configure did not produce ${_required}")
  endif()
endforeach()

file(STRINGS "${_plugins_makefile}" _modules REGEX "^SASL_MECHS =")
if(_modules MATCHES "(^| )libgs2[.]la( |$)")
  file(STRINGS "${_lib_makefile}" _static_objects REGEX "^SASL_STATIC_OBJS =")
  if(NOT _static_objects MATCHES "(^| )gs2[.]o( |$)")
    message(FATAL_ERROR "Cyrus SASL GS2 module is missing from the static archive")
  endif()
  file(STRINGS "${_config}" _gs2_defined REGEX "^#define STATIC_GS2 ")
  if(NOT _gs2_defined)
    file(APPEND "${_config}" "\n#define STATIC_GS2 1\n")
  endif()
endif()
