if(NOT DEFINED CPKT_POSTGRESQL_SOURCE_DIR OR CPKT_POSTGRESQL_SOURCE_DIR STREQUAL "")
  message(FATAL_ERROR "CPKT_POSTGRESQL_SOURCE_DIR is required")
endif()

set(oauth_source "${CPKT_POSTGRESQL_SOURCE_DIR}/src/interfaces/libpq/fe-auth-oauth.c")
if(NOT EXISTS "${oauth_source}")
  message(FATAL_ERROR "PostgreSQL OAuth loader source is missing: ${oauth_source}")
endif()

file(READ "${oauth_source}" oauth_contents)
set(upstream_loader "LIBDIR \"/libpq-oauth-\"")
set(relocatable_loader "\"@loader_path/libpq-oauth-\"")
if(oauth_contents MATCHES "@loader_path/libpq-oauth-")
  return()
endif()
string(FIND "${oauth_contents}" "${upstream_loader}" loader_position)
if(loader_position EQUAL -1)
  message(FATAL_ERROR "PostgreSQL OAuth loader source has changed; update the relocatable module patch")
endif()
string(REPLACE "${upstream_loader}" "${relocatable_loader}" oauth_contents "${oauth_contents}")
file(WRITE "${oauth_source}" "${oauth_contents}")
