if(NOT DEFINED CPKT_EXTERNAL_ROOT OR CPKT_EXTERNAL_ROOT STREQUAL "")
  message(FATAL_ERROR "CPKT_EXTERNAL_ROOT is required")
endif()

function(cpkt_remove_if_exists path)
  if(EXISTS "${path}" OR IS_SYMLINK "${path}")
    file(REMOVE_RECURSE "${path}")
  endif()
endfunction()

function(cpkt_prune_doc_tree install_root)
  set(doc_root "${install_root}/share/doc")
  if(NOT EXISTS "${doc_root}")
    return()
  endif()

  file(GLOB doc_entries RELATIVE "${doc_root}" "${doc_root}/*")
  foreach(doc_entry IN LISTS doc_entries)
    if(NOT doc_entry STREQUAL "libcpkt-third-party")
      file(REMOVE_RECURSE "${doc_root}/${doc_entry}")
    endif()
  endforeach()
endfunction()

function(cpkt_prune_install_tree install_root)
  if(NOT EXISTS "${install_root}")
    return()
  endif()

  cpkt_remove_if_exists("${install_root}/bin")
  cpkt_remove_if_exists("${install_root}/lib/pkgconfig")
  cpkt_remove_if_exists("${install_root}/lib/cmake")
  cpkt_remove_if_exists("${install_root}/share/man")
  cpkt_prune_doc_tree("${install_root}")
endfunction()

cpkt_prune_install_tree("${CPKT_EXTERNAL_ROOT}/curl/install")
cpkt_prune_install_tree("${CPKT_EXTERNAL_ROOT}/libssh2/install")
cpkt_prune_install_tree("${CPKT_EXTERNAL_ROOT}/zlib/install")
cpkt_prune_install_tree("${CPKT_EXTERNAL_ROOT}/openssl/install")
cpkt_prune_install_tree("${CPKT_EXTERNAL_ROOT}/nghttp2/install")
cpkt_prune_install_tree("${CPKT_EXTERNAL_ROOT}/cmocka/install")

cpkt_remove_if_exists("${CPKT_EXTERNAL_ROOT}/nghttp2/install/lib/libnghttp2.la")
cpkt_remove_if_exists("${CPKT_EXTERNAL_ROOT}/openssl/install/lib/engines-3")
cpkt_remove_if_exists("${CPKT_EXTERNAL_ROOT}/openssl/install/lib/ossl-modules")
